export enum RequestType {
  ExtendLicense = "تمدید پروانه",
  RevokeLicense = "لغو پروانه",
  Other = "سایر درخواست ها",
  AddNewBoard = "افزودن هیئت مدیره جدید",
  AddEmployees = "افزودن کارکنان",
  AddWorkLocation = "تاسیس شعبه",
  ChangeWorkLocation = "تغيير محل فعاليت",
  NaturalToLegal = "حقیقی به حقوقی",
  ChangeBranchManager = "تغییر مدیر شعبه",
  Vacation = "مرخصی",
  ConfirmationContract = "تایید قرارداد",
  NewStackholders = "افزودن سهامداران جدید",
  CapitalIncrease = "افزایش سرمایه",
  Reactivation = "فعالسازی مجدد میزکار حقیقی",
  CEO = "CEO",
}

export enum RequestTypeId {
  ExtendLicense = 1,
  RevokeLicense = 2,
  Other = 3,
  AddNewBoard = 4,
  AddEmployees = 5,
  AddWorkLocation = 6,
  ChangeWorkLocation = 7,
  NaturalToLegal = 8,
  ChangeBranchManager = 9,
  Vacation = 10,
  ConfirmationContract = 11,
  Reactivation = 12,
  NewStackholders = 13,
  CapitalIncrease = 14,
  CEO = 15,
}
