export const ALL_ADMISION_EXPERT = "ALL_ADMISION_EXPERT";
export const ALL_ADMISION_EXPERT_SUCCESS = "ALL_ADMISION_EXPERT_SUCCESS";
export const ALL_ADMISION_EXPERT_FAILD = "ALL_ADMISION_EXPERT_FAILD";

export const DATA_NATURAL_CARTABLE = "DATA_NATURAL_CARTABLE"; 
export const DATA_FILTER_NATURAL_CARTABLE = "DATA_FILTER_NATURAL_CARTABLE";
export const DATA_FILTER_NATURAL_CARTABLE_OUTBOX =
  "DATA_FILTER_NATURAL_CARTABLE_OUTBOX";
export const DATA_FILTER_JUDICAL_CARTABLE = "DATA_FILTER_JUDICAL_CARTABLE";
export const DATA_FILTER_LEGAL_CARTABLE = "DATA_FILTER_LEGAL_CARTABLE";
export const DATA_JUDICAL_CARTABLE = "DATA_JUDICAL_CARTABLE";
export const DATA_LEGAL_CARTABLE = "DATA_LEGAL_CARTABLE";
export const ALL_DOCUMENT_CARTABLE = "ALL_DOCUMENT_CARTABLE";
export const SUBMIT_CHEKED = "SUBMIT_CHEKED";
export const ALL_WORK_EXPERIENCE_CARTABLE = "ALL_WORK_EXPERIENCE_CARTABLE";
// export const SAVE_WORK_EXPERIENCE_CARTABLE = "SAVE_WORK_EXPERIENCE_CARTABLE";

//استعلام آزمون آداب
export const INQUIRY_PAJOOHESHKADEH = "INQUIRY_PAJOOHESHKADEH";
export const INQUIRY_PAJOOHESHKADEH_SUCCESS = "INQUIRY_PAJOOHESHKADEH_SUCCESS";
export const INQUIRY_PAJOOHESHKADEH_FAILD = "INQUIRY_PAJOOHESHKADEH_FAILD";

//استعلام گواهینامه آموزشی
export const INQUIRY_CERTIFICATIN_TRAINING = "INQUIRY_CERTIFICATIN_TRAINING";
export const INQUIRY_CERTIFICATIN_TRAINING_SUCCESS =
  "INQUIRY_CERTIFICATIN_TRAINING_SUCCESS";
export const INQUIRY_CERTIFICATIN_TRAINING_FAILD =
  "INQUIRY_CERTIFICATIN_TRAINING_FAILD";

//استعلام سوابق کاری
export const INQUIRY_LEAGACY = "INQUIRY_LEAGACY";
export const INQUIRY_LEAGACY_SUCCESS = "INQUIRY_LEAGACY_SUCCESS";
export const INQUIRY_LEAGACY_FAILD = "INQUIRY_LEAGACY_FAILD";
// سرویس شاخص ها
export const FORBIDDEN_POSITION_INFO= "FORBIDDEN_POSITION_INFO";
export const FORBIDDEN_POSITION_INFO_SUCCESS= "FORBIDDEN_POSITION_INFO_SUCCESS";
export const FORBIDDEN_POSITION_INFO_FAILED= "FORBIDDEN_POSITION_INFO_FAILED";

// گزارش شاخص ها
export const APPLICANT_FORBIDDEN_REPORT= "APPLICANT_FORBIDDEN_REPORT";
export const APPLICANT_FORBIDDEN_REPORT_SUCCESS= "APPLICANT_FORBIDDEN_REPORT_SUCCESS";
export const APPLICANT_FORBIDDEN_REPORT_FAILED= "APPLICANT_FORBIDDEN_REPORT_FAILED";

// سرویس مبنبع شاخص ها
export const FORBIDDEN_SOURCE_POSITION_INFO= "FORBIDDEN_SOURCE_POSITION_INFO";
export const FORBIDDEN_SOURCE_POSITION_INFO_SUCCESS= "FORBIDDEN_SOURCE_POSITION_INFO_SUCCESS";
export const FORBIDDEN_SOURCE_POSITION_INFO_FAILED= "FORBIDDEN_SOURCE_POSITION_INFO_FAILED";

// ثبت اطلاعات پایه شاخص ها
export const FORBIDDEN_SUBMIT_BASE_INFO= "FORBIDDEN_SUBMIT_BASE_INFO";
export const FORBIDDEN_SUBMIT_BASE_INFO_SUCCESS= "FORBIDDEN_SUBMIT_BASE_INFO_SUCCESS";
export const FORBIDDEN_SUBMIT_BASE_INFO_FAILED= "FORBIDDEN_SUBMIT_BASE_INFO_FAILED";

// لیست اطلاعات پایه شاخص ها
export const FORBIDDEN_BASE_INFO_LIST= "FORBIDDEN_BASE_INFO_LIST";
export const FORBIDDEN_BASE_INFO_LIST_SUCCESS= "FORBIDDEN_BASE_INFO_LIST_SUCCESS";
export const FORBIDDEN_BASE_INFO_LIST_FAILED= "FORBIDDEN_BASE_INFO_LIST_FAILED";


//لیست استعلام
export const INQUIRU_LIST = "INQUIRU_LIST";
export const INQUIRU_LIST_SUCCESS = "INQUIRU_LIST_SUCCESS";
export const INQUIRU_LIST_FAILD = "INQUIRU_LIST_FAILD";

//زمان مصاحبه تعیین شده
export const FETCH_INTERVIEWTIMING_APPLICANTID =
  "FETCH_INTERVIEWTIMING_APPLICANTID";
export const FETCH_INTERVIEWTIMING_APPLICANTID_SUCCESS =
  "FETCH_INTERVIEWTIMING_APPLICANTID_SUCCESS";
export const FETCH_INTERVIEWTIMING_APPLICANTID_FAILD =
  "FETCH_INTERVIEWTIMING_APPLICANTID_FAILD";

//حذف زمان مصاحبه تعیین شده
export const REMOVE_INTERVIEWTIMING_APPLICANTID =
  "REMOVE_INTERVIEWTIMING_APPLICANTID";
export const REMOVE_INTERVIEWTIMING_APPLICANTID_SUCCESS =
  "REMOVE_INTERVIEWTIMING_APPLICANTID_SUCCESS";
export const REMOVE_INTERVIEWTIMING_APPLICANTID_FAILD =
  "REMOVE_INTERVIEWTIMING_APPLICANTID_FAILD";

//لیست وضعیت ها
export const STATUS_LIST = "STATUS_LIST";
export const STATUS_LIST_SUCCESS = "STATUS_LIST_SUCCESS";
export const STATUS_LIST_FAILD = "STATUS_LIST_FAILD";

//لیست بایگانی شده ها
export const ARCHIVED_LIST = "ARCHIVED_LIST";
export const ARCHIVED_LIST_SUCCESS = "ARCHIVED_LIST_SUCCESS";
export const ARCHIVED_LIST_FAILD = "ARCHIVED_LIST_FAILD";

//لیست کل دوره ها
export const ALL_COURSE = "ALL_COURSE";
export const ALL_COURSE_SUCCESS = "ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAILD = "ALL_COURSE_FAILD";

//دریافت اطلاعات شرکت
export const FETCH_ADJUSTER_COMPANY_INFO_LEGAL = "FETCH_ADJUSTER_COMPANY_INFO_LEGAL";
export const FETCH_ADJUSTER_COMPANY_INFO_LEGAL_SUCCESS = "FETCH_ADJUSTER_COMPANY_INFO_LEGAL_SUCCESS";
export const FETCH_ADJUSTER_COMPANY_INFO_LEGAL_FAILED = "FETCH_ADJUSTER_COMPANY_INFO_LEGAL_FAILED";

//دریافت اطلاعات شعبه ها
export const APPLICANT_WORK_LOCATION_INFO = "APPLICANT_WORK_LOCATION_INFO";
export const APPLICANT_WORK_LOCATION_INFO_SUCCESS = "APPLICANT_WORK_LOCATION_INFO_SUCCESS";
export const APPLICANT_WORK_LOCATION_INFO_FAILD = "APPLICANT_WORK_LOCATION_INFO_FAILD";

//لیست شعبه ها

export const APPLICANT_WORK_BRANCH_LIST = "APPLICANT_WORK_BRANCH_LIST";
export const APPLICANT_WORK_BRANCH_LIST_SUCCESS = "APPLICANT_WORK_BRANCH_LIST_SUCCESS";
export const APPLICANT_WORK_BRANCH_LIST_FAILD = "APPLICANT_WORK_BRANCH_LIST_FAILD";

//لیست کل دوره ها براساس نوع ارزیاب
export const ALL_COURSE_ADJUSTER_TYPE = "ALL_COURSE_ADJUSTER_TYPE";
export const ALL_COURSE_ADJUSTER_TYPE_SUCCESS =
  "ALL_COURSE_ADJUSTER_TYPE_SUCCESS";
export const ALL_COURSE_ADJUSTER_TYPE_FAILD = "ALL_COURSE_ADJUSTER_TYPE_FAILD";

//لیست کل زمینه های تخصصی
export const AdJUSTMENT_FIELD_PARENT_LIST = "AdJUSTMENT_FIELD_PARENT_LIST";
export const AdJUSTMENT_FIELD_PARENT_LIST_SUCCESS =
  "AdJUSTMENT_FIELD_PARENT_LIST_SUCCESS";
export const AdJUSTMENT_FIELD_PARENT_LIST_FAILD =
  "AdJUSTMENT_FIELD_PARENT_LIST_FAILD";

//گزارش اماری
export const ADD_STATICAL_REPORT = "ADD_STATICAL_REPORT";
export const ADD_STATICAL_REPORT_SUCCESS = "ADD_STATICAL_REPORT_SUCCESS";
export const ADD_STATICAL_REPORT_FAILD = "ADD_STATICAL_REPORT_FAILD";

//جزییات گزارش
export const DETAIL_STATICAL_REPORT = "DETAIL_STATICAL_REPORT";
export const DETAIL_STATICAL_REPORT_SUCCESS = "DETAIL_STATICAL_REPORT_SUCCESS";
export const DETAIL_STATICAL_REPORT_FAILD = "DETAIL_STATICAL_REPORT_FAILD";
export const DETAIL_STATICAL_REPORT_FAILD_INFO =
  "DETAIL_STATICAL_REPORT_FAILD_INFO";

//پیام های خروجی
export const SMS_OUT_BOX_LIST = "SMS_OUT_BOX_LIST";
export const SMS_OUT_BOX_LIST_SUCCESS = "SMS_OUT_BOX_LIST_SUCCESS";
export const SMS_OUT_BOX_LIST_FAILD = "SMS_OUT_BOX_LIST_FAILD";

// پیام های خروجی هر ارزیاب
export const SMS_OUT_BOX_LIST_APPLICANT_ID = "SMS_OUT_BOX_LIST_APPLICANT_ID";
export const SMS_OUT_BOX_LIST_APPLICANT_ID_SUCCESS =
  "SMS_OUT_BOX_LIST_APPLICANT_ID_SUCCESS";
export const SMS_OUT_BOX_LIST_APPLICANT_ID_FAILD =
  "SMS_OUT_BOX_LIST_APPLICANT_ID_FAILD";

//پیامک های کارتابل مدیریت
export const SUPERVISION_SMS_OUT_BOX_LIST_APPLICANT_ID =
  " SUPERVISION_SMS_OUT_BOX_LIST_APPLICANT_ID";
export const SUPERVISION_SMS_OUT_BOX_LIST_APPLICANT_ID_SUCCESS =
  "SUPERVISION_SMS_OUT_BOX_LIST_APPLICANT_ID_SUCCESS";
export const SUPERVISION_SMS_OUT_BOX_LIST_APPLICANT_ID_FAILD =
  "SUPERVISION_SMS_OUT_BOX_LIST_APPLICANT_ID_FAILD";

  //پیامک های نظارت
export const SUPERVISION_SMS_OUT_BOX_LIST =
" SUPERVISION_SMS_OUT_BOX_LIST";
export const SUPERVISION_SMS_OUT_BOX_LIST_SUCCESS =
"SUPERVISION_SMS_OUT_BOX_LIST_SUCCESS";
export const SUPERVISION_SMS_OUT_BOX_LIST_FAILD =
"SUPERVISION_SMS_OUT_BOX_LIST_FAILD";

//لیست پیامک های گروهی
export const SMS_BATCH_SEND = "SMS_BATCH_SEND";
export const SMS_BATCH_SEND_SUCCESS = "SMS_BATCH_SEND_SUCCESS";
export const SMS_BATCH_SEND_FAILD = "SMS_BATCH_SEND_FAILD";


//لیست پیامک های انبوه
export const SMS_SEND_SPECIFIC_TYPE = "SMS_SEND_SPECIFIC_TYPE";
export const SMS_SEND_SPECIFIC_TYPE_SUCCESS = "SMS_SEND_SPECIFIC_TYPE_SUCCESS";
export const SMS_SEND_SPECIFIC_TYPE_FAILD = "SMS_SEND_SPECIFIC_TYPE_FAILD";



//ارسال پیامکهای گروهی کارتابل مدیریت
export const SUPERVISION_SMS_BATCH_SEND = "SUPERVISION_SMS_BATCH_SEND";
export const SUPERVISION_SMS_BATCH_SEND_SUCCESS = "SUPERVISION_SMS_BATCH_SEND_SUCCESS";
export const SUPERVISION_SMS_BATCH_SEND_FAILD = "SUPERVISION_SMS_BATCH_SEND_FAILD";


//لیست پیام های ارسالی گزارش
export const SMS_BATCH_SEND_REPORT_CARTABLE = "SMS_BATCH_SEND_REPORT_CARTABLE";
export const SMS_BATCH_SEND_REPORT_CARTABLE_SUCCESS =
  "SMS_BATCH_SEND_REPORT_CARTABLE_SUCCESS";
export const SMS_BATCH_SEND_REPORT_CARTABLE_FAILD =
  "SMS_BATCH_SEND_REPORT_CARTABLE_FAILD";

export const RESET_IMAGE_STATE = "RESET_IMAGE_STATE";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILD = "USER_LOGIN_FAILD";

//اضافه کردن زمان مصاحبه
export const ADD_INTERVIEW_TIME = "ADD_INTERVIEW_TIME";
export const ADD_INTERVIEW_TIME_SUCCESS = "ADD_INTERVIEW_TIME_SUCCESS";
export const ADD_INTERVIEW_TIME_FAILD = "ADD_INTERVIEW_TIME_FAILD";

//لیست زمان های مصاحبه
export const LIST_INTERVIEW_TIME = "LIST_INTERVIEW_TIME";
export const LIST_INTERVIEW_TIME_SUCCESS = "LIST_INTERVIEW_TIME_SUCCESS";
export const LIST_INTERVIEW_TIME_FAILD = "LIST_INTERVIEW_TIME_FAILD";

//interview TimingSeason
export const LIST_SEASON_INTERVIEW_TIMING = "LIST_SEASON_INTERVIEW_TIMING";
export const LIST_SEASON_INTERVIEW_TIMING_SUCCESS =
  "LIST_SEASON_INTERVIEW_TIMING_SUCCESS";
export const LIST_SEASON_INTERVIEW_TIMING_FAILD =
  "LIST_SEASON_INTERVIEW_TIMING_FAILD";

//remove interview TimingSeason
export const REMOVE_SEASON_INTERVIEW_TIMING = "REMOVE_SEASON_INTERVIEW_TIMING";
export const REMOVE_SEASON_INTERVIEW_TIMING_SUCCESS =
  "REMOVE_SEASON_INTERVIEW_TIMING_SUCCESS";
export const REMOVE_SEASON_INTERVIEW_TIMING_FAILD =
  "REMOVE_SEASON_INTERVIEW_TIMING_FAILD";

//فرم صورتجلسه مصاحبه
export const INTERVIEW_MINUTES = "INTERVIEW_MINUTES";
export const INTERVIEW_MINUTES_SUCCESS = "INTERVIEW_MINUTES_SUCCESS";
export const INTERVIEW_MINUTES_FAILD = "INTERVIEW_MINUTES_FAILD";

//آپلود فرم مصاحبه
export const INTERVIEW_MINUTES_UPLOAD = "INTERVIEW_MINUTES_UPLOAD";
export const INTERVIEW_MINUTES_UPLOAD_SUCCESS =
  "INTERVIEW_MINUTES_UPLOAD_SUCCESS";
export const INTERVIEW_MINUTES_UPLOAD_FAILD = "INTERVIEW_MINUTES_UPLOAD_FAILD";

//دانلود فرم صورتجلسه مصاحبه
export const INTERVIEW_MINUTES_DOCUMENT_FILE =
  "INTERVIEW_MINUTES_DOCUMENT_FILE";
export const INTERVIEW_MINUTES_DOCUMENT_FILE_SUCCESS =
  "INTERVIEW_MINUTES_DOCUMENT_FILE_SUCCESS";
export const INTERVIEW_MINUTES_DOCUMENT_FILE_FAILD =
  "INTERVIEW_MINUTES_DOCUMENT_FILE_FAILD";

//Cartable
export const APPLICANT_INTERVIEW_TIME = "APPLICANT_INTERVIEW_TIME";
export const APPLICANT_INTERVIEW_TIME_SUCCESS =
  "APPLICANT_INTERVIEW_TIME_SUCCESS";
export const APPLICANT_INTERVIEW_TIME_FAILD = "APPLICANT_INTERVIEW_TIME_FAILD";

//لیست سندهای کارتابل
export const DOCUMENT_APPROVE = "DOCUMENT_APPROVE";
export const DOCUMENT_APPROVE_SUCCESS = "DOCUMENT_APPROVE_SUCCESS";
export const DOCUMENT_APPROVE_FAILD = "DOCUMENT_APPROVE_FAILD";

//لیست سوابق کاری کارتابل
export const WORKEXPERIENCE_APPROVE = "WORKEXPERIENCE_APPROVE";
export const WORKEXPERIENCE_APPROVEE_SUCCESS =
  "WORKEXPERIENCE_APPROVEE_SUCCESS";
export const WORKEXPERIENCE_APPROVE_FAILD = "WORKEXPERIENCE_APPROVE_FAILD";

// کارتابل شاخص ها
export const APPLICANT_FORBIDDEN_CARTABLE_INFO= "APPLICANT_FORBIDDEN_CARTABLE_INFO";
export const APPLICANT_FORBIDDEN_CARTABLE_INFO_SUCCESS = "APPLICANT_FORBIDDEN_CARTABLE_INFO_SUCCESS";
export const APPLICANT_FORBIDDEN_CARTABLE_INFO_FAILED = "APPLICANT_FORBIDDEN_CARTABLE_INFO_FAILED";

//ارجاع کارتابل
export const CARTABLE_REFER = "CARTABLE_REFER";
export const CARTABLE_REFER_SUCCESS = "CARTABLE_REFER_SUCCESS";
export const CARTABLE_REFER_FAILD = "CARTABLE_REFER_FAILD";

//غیبت از نصاحبه
export const CARTABLE_ABSENCE = "CARTABLE_ABSENCE";
export const CARTABLE_ABSENCE_SUCCESS = "CARTABLE_ABSENCE_SUCCESS";
export const CARTABLE_ABSENCE_FAILD = "CARTABLE_ABSENCE_FAILD";

//مرجوع کارتابل
export const CARTABLE_REJECT = "CARTABLE_REJECT";
export const CARTABLE_REJECT_SUCCESS = "CARTABLE_REJECT_SUCCESS";
export const CARTABLE_REJECT_FAILD = "CARTABLE_REJECT_FAILD";

//بایگانی کارتابل
export const CARTABLE_ARCHIVE = "CARTABLE_ARCHIVE";
export const CARTABLE_ARCHIVE_SUCCESS = "CARTABLE_ARCHIVE_SUCCESS";
export const CARTABLE_ARCHIVE_FAILD = "CARTABLE_ARCHIVE_FAILD";

//لیست کارتابل حقیقی
export const LIST_NATURAL_CARTABLE = "LIST_NATURAL_CARTABLE";
export const LIST_NATURAL_CARTABLE_SUCCESS = "LIST_NATURAL_CARTABLE_SUCCESS";
export const LIST_NATURAL_CARTABLE_FAILD = "LIST_NATURAL_CARTABLE_FAILD";

// لیست کارتابل حقوقی
export const LIST_LEGAL_CARTABLE = "LIST_LEGAL_CARTABLE";
export const LIST_LEGAL_CARTABLE_SUCCESS = "LIST_LEGAL_CARTABLE_SUCCESS";
export const LIST_LEGAL_CARTABLE_FAILD = "LIST_LEGAL_CARTABLE_FAILD";

// جزییات کارتابل حقوقی
export const PERSONAL_INFO_LEGAL_DETAIL = "PERSONAL_INFO_LEGAL_DETAIL";
export const PERSONAL_INFO_LEGAL_DETAIL_SUCCESS =
  "PERSONAL_INFO_LEGAL_DETAIL_SUCCESS";
export const PERSONAL_INFO_LEGAL_DETAIL_FAILD =
  "PERSONAL_INFO_LEGAL_DETAIL_FAILD";

// لیست کارتابل دادگستری
export const LIST_JUDICAL_CARTABLE = "LIST_JUDICAL_CARTABLE";
export const LIST_JUDICAL_CARTABLE_SUCCESS = "LIST_JUDICAL_CARTABLE_SUCCESS";
export const LIST_JUDICAL_CARTABLE_FAILD = "LIST_JUDICAL_CARTABLE_FAILD";

//جزییات ارزیاب
export const PERSONAL_INFO_DETAIL = "PERSONAL_INFO_DETAIL";
export const PERSONAL_INFO_DETAIL_SUCCESS = "PERSONAL_INFO_DETAIL_SUCCESS";
export const PERSONAL_INFO_DETAIL_FAILD = "PERSONAL_INFO_DETAIL_FAILD";

//خروجی اکسل
export const EXCEL_OUTPUT_CARTABLE = "EXCEL_OUTPUT_CARTABLE";
export const EXCEL_OUTPUT_CARTABLE_SUCCESS = "EXCEL_OUTPUT_CARTABLE_SUCCESS";
export const EXCEL_OUTPUT_CARTABLE_FAILD = "EXCEL_OUTPUT_CARTABLE_FAILD";

// نامه چارگون
export const CHARGON_LETTER = "CHARGON_LETTER";
export const CHARGON_LETTER_SUCCESS = "CHARGON_LETTER_SUCCESS";
export const CHARGON_LETTER_FAILD = "CHARGON_LETTER_FAILD";

// تمدید نامه
export const EXTEND_CHARGON_LETTER = "EXTEND_CHARGON_LETTER";
export const EXTEND_CHARGON_LETTER_SUCCESS = "EXTEND_CHARGON_LETTER_SUCCESS";
export const EXTEND_CHARGON_LETTER_FAILD = "EXTEND_CHARGON_LETTER_FAILD";

// ثبت چارگون
export const SUBMIT_CHARGON = "SUBMIT_CHARGON";
export const SUBMIT_CHARGON_SUCCESS = "SUBMIT_CHARGON_SUCCESS";
export const SUBMIT_CHARGON_FAILD = "SUBMIT_CHARGON_FAILD";
// تایید چارگون
export const CONFIRM_CHARGON_LETTER = "CONFIRM_CHARGON_LETTER";
export const CONFIRM_CHARGON_LETTER_SUCCESS = "CONFIRM_CHARGON_LETTER_SUCCESS";
export const CONFIRM_CHARGON_LETTER_FAILD = "CONFIRM_CHARGON_LETTER_FAILD";

//دانلود اطلاعات پرونده
export const INFORMATION_FILE = "INFORMATION_FILE";
export const INFORMATION_FILE_SUCCESS = "INFORMATION_FILE_SUCCESS";
export const INFORMATION_FILE_FAILD = "INFORMATION_FILE_FAILD";

//دریافت پروانه ارزیاب
export const DOWNLOAD_LICENCE_ADJUSTER = "DOWNLOAD_LICENCE_ADJUSTER";
export const DOWNLOAD_LICENCE_ADJUSTER_SUCCESS =
  "DOWNLOAD_LICENCE_ADJUSTER_SUCCESS";
export const DOWNLOAD_LICENCE_ADJUSTER_FAILD =
  "DOWNLOAD_LICENCE_ADJUSTER_FAILD";

//صدور پروانه و نامه چارگون
export const LICENCE_ISSU = "LICENCE_ISSU";
export const LICENCE_ISSU_SUCCESS = "LICENCE_ISSU_SUCCESS";
export const LICENCE_ISSU_FAILD = "LICENCE_ISSU_FAILD";

//صادر کننده کدارزیاب
export const LICENSE_ISSUER = "LICENSE_ISSUER";
export const LICENSE_ISSUER_SUCCESS = "LICENSE_ISSUER_SUCCESS";
export const LICENSE_ISSUER_FAILD = "LICENSE_ISSUER_FAILD";

//دانلود سوابق کاری
export const DOWNLOAD_WORK_EXPERIENCE = "DOWNLOAD_WORK_EXPERIENCE";
export const DOWNLOAD_WORK_EXPERIENCE_SUCCESS =
  "DOWNLOAD_WORK_EXPERIENCE_SUCCESS";
export const DOWNLOAD_WORK_EXPERIENCE_FAILD = "DOWNLOAD_WORK_EXPERIENCE_FAILD";

//دانلود اسناد
export const DOWNLOAD_DOCUMENT = "DOWNLOAD_DOCUMENT";
export const DOWNLOAD_DOCUMENT_SUCCESS = "DOWNLOAD_DOCUMENT_SUCCESS";
export const DOWNLOAD_DOCUMENT_FAILD = "DOWNLOAD_DOCUMENT_FAILD";
//حذف اسناد
export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT";
export const REMOVE_DOCUMENT_SUCCESS = "REMOVE_DOCUMENT_SUCCESS";
export const REMOVE_DOCUMENT_FAILD = "REMOVE_DOCUMENT_FAILD";

//پیوست ها
export const ATTACHMENT = "ATTACHMENT";
export const ATTACHMENT_SUCCESS = "ATTACHMENT_SUCCESS";
export const ATTACHMENT_FAILD = "ATTACHMENT_FAILD";

//لیست پیوست ها
export const ATTACHMENT_LIST = "ATTACHMENT_LIST";
export const ATTACHMENT_LIST_SUCCESS = "ATTACHMENT_LIST_SUCCESS";
export const ATTACHMENT_LIST_FAILD = "ATTACHMENT_LIST_FAILD";

//دانلود پیوست
export const ATTACHMENT_DOWNLOAD = "ATTACHMENT_DOWNLOAD";
export const ATTACHMENT_DOWNLOAD_SUCCESS = "ATTACHMENT_DOWNLOAD_SUCCESS";
export const ATTACHMENT_DOWNLOAD_FAILD = "ATTACHMENT_DOWNLOAD_FAILD";

//حذف پیوست
export const ATTACHMENT_REMOVE = "ATTACHMENT_REMOVE";
export const ATTACHMENT_REMOVE_SUCCESS = "ATTACHMENT_REMOVE_SUCCESS";
export const ATTACHMENT_REMOVE_FAILD = "ATTACHMENT_REMOVE_FAILD";

//زیر رشته
export const SUB_FIELD = "SUB_FIELD";
export const SUB_FIELD_SUCCESS = "SUB_FIELD_SUCCESS";
export const SUB_FIELD_FAILD = "SUB_FIELD_FAILD";

//اصافه کردن یادداشت
export const ADD_NOTE = "ADD_NOTE";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILD = "ADD_NOTE_FAILD";

//لیست یادداشت ها
export const NOTE_LIST = "NOTE_LIST";
export const NOTE_LIST_SUCCESS = "NOTE_LIST_SUCCESS";
export const NOTE_LIST_FAILD = "NOTE_LIST_FAILD";

//حذف یادداشت
export const NOTE_REMOVE = "NOTE_REMOVE";
export const NOTE_REMOVE_SUCCESS = "NOTE_REMOVE_SUCCESS";
export const NOTE_REMOVE_FAILD = "NOTE_REMOVE_FAILD";

//Interview Session
export const INTERVIEW_SESSION = "INTERVIEW_SESSION";
export const INTERVIEW_SESSION_SUCCESS = "INTERVIEW_SESSION_SUCCESS";
export const INTERVIEW_SESSION_FAILD = "INTERVIEW_SESSION_FAILD";

//ارسال مدارک
export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILD = "UPLOAD_DOCUMENT_FAILD";

//آپدیت مدارک
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";
export const UPDATE_DOCUMENT_FAILD = "UPDATE_DOCUMENT_FAILD";

//تاریخچه مدارک
export const HISTORY_DOCUMENT = "HISTORY_DOCUMENT";
export const HISTORY_DOCUMENT_SUCCESS = "HISTORY_DOCUMENT_SUCCESS";
export const HISTORY_DOCUMENT_FAILD = "HISTORY_DOCUMENT_FAILD";

//لیست سوالات و مصاحبه کننده ها
export const LIST_QUESTION = "LIST_QUESTION";
export const LIST_QUESTION_SUCCESS = "LIST_QUESTION_SUCCESS";
export const LIST_QUESTION_FAILD = "LIST_QUESTION_FAILD";

//میانگین نمرات
export const CALCULATE_SCORE = "CALCULATE_SCORE";
export const CALCULATE_SCORE_SUCCESS = "CALCULATE_SCORE_SUCCESS";
export const CALCULATE_SCORE_FAILD = "CALCULATE_SCORE_FAILD";

//ذخیره نمره
export const ADD_INTERVIEWER_SCORE = "ADD_INTERVIEWER_SCORE";
export const ADD_INTERVIEWER_SCORE_SUCCESS = "ADD_INTERVIEWER_SCORE_SUCCESS";
export const ADD_INTERVIEWER_SCORE_FAILD = "ADD_INTERVIEWER_SCORE_FAILD";

// گرفتن نمرات
export const FETCH_INTERVIEWER_SCORE = "FETCH_INTERVIEWER_SCORE";
export const FETCH_INTERVIEWER_SCORE_SUCCESS =
  "FETCH_INTERVIEWER_SCORE_SUCCESS";
export const FETCH_INTERVIEWER_SCORE_FAILD = "FETCH_INTERVIEWER_SCORE_FAILD";

// آپدیت نمرات
export const UPDATE_INTERVIEWER_SCORE = "UPDATE_INTERVIEWER_SCORE";
export const UPDATE_INTERVIEWER_SCORE_SUCCESS =
  "UPDATE_INTERVIEWER_SCORE_SUCCESS";
export const UPDATE_INTERVIEWER_SCORE_FAILD = "UPDATE_INTERVIEWER_SCORE_FAILD";

//زمینه تخصصی در ثبت نمره
export const ADD_FIELD_INTERVIEWER = "ADD_FIELD_INTERVIEWER";
export const ADD_FIELD_INTERVIEWER_SUCCESS = "ADD_FIELD_INTERVIEWER_SUCCESS";
export const ADD_FIELD_INTERVIEWER_FAILD = "FIELD_INTERVIEWER_FAILD";

//گرفتن زمینه و زیرزمینه در رشته تخصصی
export const FIELD_INTERVIEWER = "FETCH_FIELD_INTERVIEWER";
export const FIELD_INTERVIEWER_SUCCESS = "FIELD_INTERVIEWER_SUCCESS";
export const FIELD_INTERVIEWER_FAILD = "FIELD_INTERVIEWER_FAILD";

//دعوت به مصاحبه
export const INVITATION_INTERVIEW = "INVITATION_INTERVIEW";
export const INVITATION_INTERVIEW_SUCCESS = "INVITATION_INTERVIEW_SUCCESS";
export const INVITATION_INTERVIEW_FAILD = "INVITATION_INTERVIEW_FAILD";

//courses80 Score
export const COURS80_SCORE = "COURS80_SCORE";
export const COURS80_SCORE_SUCCESS = "COURS80_SCORE_SUCCESS";
export const COURS80_SCORE_FAILD = "COURS80_SCORE_FAILD";

// list Board member
export const LIST_BOARD_MEMBER = "LIST_BOARD_MEMBER";
export const LIST_BOARD_MEMBER_SUCCESS = "LIST_BOARD_MEMBER_SUCCESS";
export const LIST_BOARD_MEMBER_FAILD = "LIST_BOARD_MEMBER_FAILD";
export const RESET_LIST_BOARD_MEMBER = "RESET_LIST_BOARD_MEMBER";

//description Board member
export const DESCRIPTION_BOARD_MEMBER = "DESCRIPTION_BOARD_MEMBER";
export const DESCRIPTION_BOARD_MEMBER_SUCCESS =
  "DESCRIPTION_BOARD_MEMBER_SUCCESS";
export const DESCRIPTION_BOARD_MEMBER_FAILD = "DESCRIPTION_BOARD_MEMBER_FAILD";

//گزارش کارتابل
export const CARTABLE_REPORT_ALL_INFO = "CARTABLE_REPORT_ALL_INFO";
export const CARTABLE_REPORT_ALL_INFO_SUCCESS =
  "CARTABLE_REPORT_ALL_INFO_SUCCESS";
export const CARTABLE_REPORT_ALL_INFO_FAILED =
  "CARTABLE_REPORT_ALL_INFO_FAILED";
//گزارش آماری
export const STATISTIC_REPORT_ALL_INFO = "STATISTIC_REPORT_ALL_INFO";
export const STATISTIC_REPORT_ALL_INFO_SUCCESS =
  "STATISTIC_REPORT_ALL_INFO_SUCCESS";
export const STATISTIC_REPORT_ALL_INFO_FAILED =
  "STATISTIC_REPORT_ALL_INFO_FAILED";

//کارتابل مدیریت حقیقی و دادگستری
export const REPORT_NATURAL_JUDICAL_EXISTING_EVALUATOR =
  "REPORT_NATURAL_JUDICAL_EXISTING_EVALUATOR";
export const REPORT_NATURAL_JUDICAL_EXISTING_EVALUATOR_SUCCESS =
  "REPORT_NATURAL_JUDICAL_EXISTING_EVALUATOR_SUCCESS";
export const REPORT_NATURAL_JUDICAL_EXISTING_EVALUATOR_FAILED =
  "REPORT_NATURAL_JUDICAL_EXISTING_EVALUATOR_FAILED";

//کارتابل مدیریت حقوقی
export const REPORT_LEGAL_EXISTING_EVALUATOR =
  "REPORT_LEGAL_EXISTING_EVALUATOR";
export const REPORT_LEGAL_EXISTING_EVALUATOR_SUCCESS =
  "REPORT_LEGAL_EXISTING_EVALUATOR_SUCCESS";
export const REPORT_LEGAL_EXISTING_EVALUATOR_FAILED =
  "REPORT_LEGAL_EXISTING_EVALUATOR_FAILED";

//دانلود گزارش کارتابل
export const CARTABLE_REPORT_ALL_INFO_EXCEL = "CARTABLE_REPORT_ALL_INFO_EXCEL";
export const CARTABLE_REPORT_ALL_INFO_EXCEL_SUCCESS =
  "CARTABLE_REPORT_ALL_INFO_EXCEL_SUCCESS";
export const CARTABLE_REPORT_ALL_INFO_EXCEL_FAILED =
  "CARTABLE_REPORT_ALL_INFO_EXCEL_FAILED";

  //دانلود اکسل مدیریت کارتابل

export const CARTABLE_MANAGEMENT_EXCEL="CARTABLE_MANAGEMENT_EXCEL";
export const CARTABLE_MANAGEMENT_EXCEL_SUCCESS =
  "CARTABLE_MANAGEMENT_EXCEL_SUCCESS";
export const CARTABLE_MANAGEMENT_EXCEL_FAILED =
  "CARTABLE_MANAGEMENT_EXCEL_FAILED";

export const COLUMN_FILTER_DATA_NATURAL_ADD = "COLUMN_FILTER_DATA_NATURAL_ADD";
export const COLUMN_FILTER_DATA_NATURAL_REMOVE =
  "COLUMN_FILTER_DATA_NATURAL_REMOVE";

export const COLUMN_FILTER_DATA_LEGAL_ADD = "COLUMN_FILTER_DATA_LEGAL_ADD";
export const COLUMN_FILTER_DATA_LEGAL_REMOVE =
  "COLUMN_FILTER_DATA_LEGAL_REMOVE";

export const COLUMN_FILTER_DATA_JUDICIAL_ADD =
  "COLUMN_FILTER_DATA_JUDICIAL_ADD";
export const COLUMN_FILTER_DATA_JUDICIAL_REMOVE =
  "COLUMN_FILTER_DATA_JUDICIAL_REMOVE";

export const GET_BOARD_MEMBER_LIST_REQUEST = "GET_BOARD_MEMBER_LIST_REQUEST";
export const GET_BOARD_MEMBER_LIST_REQUEST_SUCCESS =
  "GET_BOARD_MEMBER_LIST_REQUEST_SUCCESS";
export const GET_BOARD_MEMBER_LIST_REQUEST_FAILED =
  "GET_BOARD_MEMBER_LIST_REQUEST_FAILED";

/**
 * FileAssigner
 *
 */

//لیست پرونده های حقیقی و دادگستری
export const BASKET_NATURAL_JUDICAL_LIST = "BASKET_NATURAL_JUDICAL_LIST";
export const BASKET_NATURAL_JUDICAL_LIST_SUCCESS =
  "BASKET_NATURAL_JUDICAL_LIST_SUCCESS";
export const BASKET_NATURAL_JUDICAL_LIST_FAILED =
  "BASKET_NATURAL_JUDICAL_LIST_FAILED";

//لیست پرونده های حقوقی
export const BASKET_LEGAL_LIST = "BASKET_LEGAL_LIST";
export const BASKET_LEGAL_LIST_SUCCESS = "BASKET_LEGAL_LIST_SUCCESS";
export const BASKET_LEGAL_LIST_FAILED = "BASKET_LEGAL_LIST_FAILED";

//لیست کارشناسان
export const ADMISSTON_LIST = "ADMISSTON_LIST";
export const ADMISSTON_LIST_SUCCESS = "ADMISSTON_LIST_SUCCESS";
export const ADMISSTON_LIST_FAILED = "ADMISSTON_LIST_FAILED";

//ارزیاب تخصیص داده شده به کارشناس
export const BASKET_ASSIGN_ADMISSTION = "BASKET_ASSIGN_ADMISSTION";
export const BASKET_ASSIGN_ADMISSTION_SUCCESS =
  "BASKET_ASSIGN_ADMISSTION_SUCCESS";
export const BASKET_ASSIGN_ADMISSTION_FAILED =
  "BASKET_ASSIGN_ADMISSTION_FAILED";

export const GET_USERS_FOR_CARTABLE_REPORT = "GET_USERS_FOR_CARTABLE_REPORT";
export const GET_USERS_FOR_CARTABLE_REPORT_SUCCESS =
  "GET_USERS_FOR_CARTABLE_REPORT_SUCCESS";
export const GET_USERS_FOR_CARTABLE_REPORT_FAILED =
  "GET_USERS_FOR_CARTABLE_REPORT_FAILED";

export const SWAP_USERS_FROM_REPORT_TABLE = "SWAP_USERS_FROM_REPORT_TABLE";
export const SWAP_USERS_FROM_REPORT_TABLE_SUCCESS =
  "SWAP_USERS_FROM_REPORT_TABLE_SUCCESS";
export const SWAP_USERS_FROM_REPORT_TABLE_FAILED =
  "SWAP_USERS_FROM_REPORT_TABLE_FAILED";

export const FIELD_INFO_DETAIL = "FIELD_INFO_DETAIL";
export const FIELD_INFO_DETAIL_SUCCESS = "FIELD_INFO_DETAIL_SUCCESS";
export const FIELD_INFO_DETAIL_FAILED = "FIELD_INFO_DETAIL_FAILED";


//گرفتن اطلاعات حقوقی
export const FETCH_COMPANY_BASE_INFO_LEGAL = "FETCH_COMPANY_BASE_INFO_LEGAL";
export const FETCH_COMPANY_BASE_INFO_LEGAL_SUCCESS = "FETCH_COMPANY_BASE_INFO_LEGAL_SUCCESS";
export const FETCH_COMPANY_BASE_INFO_LEGAL_FAILED = "FETCH_COMPANY_BASE_INFO_LEGAL_FAILED";

//ویرایش اطلاعات حقوقی
export const EDIT_COMPANY_BASE_INFO_LEGAL = "EDIT_COMPANY_BASE_INFO_LEGAL";
export const EDIT_COMPANY_BASE_INFO_LEGAL_SUCCESS = "EDIT_COMPANY_BASE_INFO_LEGAL_SUCCESS";
export const EDIT_COMPANY_BASE_INFO_LEGAL_FAILED = "EDIT_COMPANY_BASE_INFO_LEGAL_FAILED";
