export const TYPE_REQUSET = "TYPE_REQUSET";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_CEO = "SET_CEO";
export const SET_STOCK_HOLDER = "SET_STOCK_HOLDER";
export const SET_BRANCH_MANAGER = "SET_BRANCH_MANAGER";
export const SET_CAPITAL_INCREASE = "SET_CAPITAL_INCREASE";
export const SET_COOPERATION_END_DATE = "SET_COOPERATION_END_DATE";
export const SET_BOARD_MEMEBER_BOSS = "SET_BOARD_MEMEBER_BOSS";
export const SET_ESTABLISH_BRANCH = "SET_ESTABLISH_BRANCH";
export const CHANGE_WORK_LOCATION = "CHANGE_WORK_LOCATION";
export const SET_BOARD_MEMBER = "SET_BOARD_MEMBER";
export const SET_BOARD_MEMBER_DEPUTY = "SET_BOARD_MEMBER_DEPUTY";
// export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SET_LIST_REQUEST = "SET_LIST_REQUEST";
export const SET_FILES = "SET_FILES";
export const APPLICANT_REQUSET_ID = "APPLICANT_REQUSET_ID";
export const APPLICANT_REQUSET_ID_SUCCESS = "APPLICANT_REQUSET_ID_SUCCESS";
export const APPLICANT_REQUSET_ID_FAILD = "APPLICANT_REQUSET_ID_FAILD";

//لیست مدارک مورد نیاز درخواستها
export const APPLICANT_RQQUEST_TYPE_DOCUMENT_LIST = "APPLICANT_RQQUEST_TYPE_DOCUMENT_LIST";
export const APPLICANT_RQQUEST_TYPE_DOCUMENT_LIST_SUCCESS = "APPLICANT_RQQUEST_TYPE_DOCUMENT_LIST_SUCCESS";
export const APPLICANT_RQQUEST_TYPE_DOCUMENT_LIST_FAILD = "APPLICANT_RQQUEST_TYPE_DOCUMENT_LIST_FAILD";
//بارگذاری آواتار اعلانات
export const NOTIFICATION_AVATAR_FILE = "NOTIFICATION_AVATAR_FILE";
export const NOTIFICATION_AVATAR_FILE_SUCCESS = "NOTIFICATION_AVATAR_FILE_SUCCESS";
export const NOTIFICATION_AVATAR_FILE_FAILD = "NOTIFICATION_AVATAR_FILE_FAILD";

//ایجاد میزکار ارزیاب
export const USER_DESKTOP = "USER_DESKTOP";
export const USER_DESKTOP_SUCCESS = "USER_DESKTOP_SUCCESS";
export const USER_DESKTOP_FAILD = "USER_DESKTOP_FAILD";

//دریافت لیست اعلامیه ها
export const NOTIFICATIONS_LIST = "NOTIFICATIONS_LIST"
export const NOTIFICATIONS_LIST_SUCCESS = "NOTIFICATIONS_LIST_SUCCESS"
export const NOTIFICATIONS_LIST_FAILD = "NOTIFICATIONS_LIST_FAILD"

//دریافت اطلاعات اعلامیه ها
export const NOTIFICATIONS_DETAILS = "NOTIFICATIONS_DETAILS"
export const NOTIFICATIONS_DETAILS_SUCCESS = "NOTIFICATIONS_DETAILS_SUCCESS"
export const NOTIFICATIONS_DETAILS_FAILD = "NOTIFICATIONS_DETAILS_FAILD"

//ارسال لیست اعلامیه ها
export const SUBMIT_NOTIFICATIONS = "SUBMIT_NOTIFICATIONS"
export const SUBMIT_NOTIFICATIONS_SUCCESS = "SUBMIT_NOTIFICATIONS_SUCCESS"
export const SUBMIT_NOTIFICATIONS_FAILD = "SUBMIT_NOTIFICATIONS_FAILD"

//کارهای انجام شده ارزیاب
export const ADJUSTER_PORTFOILO = "ADJUSTER_PORTFOILO";
export const ADJUSTER_PORTFOILO_SUCCESS = "ADJUSTER_PORTFOILO_SUCCESS";
export const ADJUSTER_PORTFOILO_FAILD = "ADJUSTER_PORTFOILO_FAILD";

//پایان همکاری عضو هیئت مدیره
export const BOARD_MEMBER_END_COOPERATION = "BOARD_MEMBER_END_COOPERATION";
export const BOARD_MEMBER_END_COOPERATION_SUCCESS = "BOARD_MEMBER_END_COOPERATION_SUCCESS";
export const BOARD_MEMBER_END_COOPERATION_FAILD = "BOARD_MEMBER_END_COOPERATION_FAILD";
//پایان همکاری کارکنان
export const EMPLOYEE_END_COOPERATION = "EMPLOYEE_END_COOPERATION";
export const EMPLOYEE_END_COOPERATION_SUCCESS = "EMPLOYEE_END_COOPERATION_SUCCESS";
export const EMPLOYEE_END_COOPERATION_FAILD = "EMPLOYEE_END_COOPERATION_FAILD";

//آپلود فایل
export const UPLOAD_FILES = "UPLOAD_FILES";
export const UPLOAD_FILES_SUCCESS = "UPLOAD_FILES_SUCCESS";
export const UPLOAD_FILES_FAILD = "UPLOAD_FILES_FAILD";

//دلایل تغییر وضعیت
export const CHANGE_STATUS_REASON = "CHANGE_STATUS_REASON";
export const CHANGE_STATUS_REASON_SUCCESS = "CHANGE_STATUS_REASON_SUCCESS";
export const CHANGE_STATUS_REASON_FAILD = "CHANGE_STATUS_REASON_FAILD";

//گرفتن وضعیت جاری
export const GET_NEXT_STATUSES = "GET_NEXT_STATUSES";
export const GET_NEXT_STATUSES_SUCCESS = "GET_NEXT_STATUSES_SUCCESS";
export const GET_NEXT_STATUSES_FAILD = "GET_NEXT_STATUSES_FAILD";

//لیست وضعیت ها
export const GET_APPLICANT_STATUS = "GET_APPLICANT_STATUS";
export const GET_APPLICANT_STATUS_SUCCESS = "GET_APPLICANT_STATUS_SUCCESS";
export const GET_APPLICANT_STATUS_FAILD = "GET_APPLICANT_STATUS_FAILD";

//لیست وضعیت های متقاضی
export const GET_APPLICANT_REQUEST_STATUS = "GET_APPLICANT_REQUEST_STATUS";
export const GET_APPLICANT_REQUEST_STATUS_SUCCESS = "GET_APPLICANT_REQUEST_STATUS_SUCCESS";
export const GET_APPLICANT_REQUEST_STATUS_FAILD = "GET_APPLICANT_REQUEST_STATUS_FAILD";
//لیست اخطارها
export const APPLICANT_WARNINGS_LIST = "APPLICANT_WARNINGS_LIST";
export const APPLICANT_WARNINGS_LIST_SUCCESS = "APPLICANT_WARNINGS_LIST_SUCCESS";
export const APPLICANT_WARNINGS_LIST_FAILD = "APPLICANT_WARNINGS_LIST_FAILD";

//ذخیره وضعیت
export const SAVE_CHANGE_STATUSES = "SAVE_CHANGE_STATUSES";
export const SAVE_CHANGE_STATUSES_SUCCESS = "SAVE_CHANGE_STATUSES_SUCCESS";
export const SAVE_CHANGE_STATUSES_FAILD = "SAVE_CHANGE_STATUSES_FAILD";

//تاریخچه تغییر وضعیت
export const STATUSES_HISTORY = "STATUSES_HISTORY";
export const STATUSES_HISTORY_SUCCESS = "STATUSES_HISTORY_SUCCESS";
export const STATUSES_HISTORY_FAILD = "STATUSES_HISTORY_FAILD";

//حذف فایل
export const REMOVE_FILE = "REMOVE_FILE";
export const REMOVE_FILE_SUCCESS = "REMOVE_FILE_SUCCESS";
export const REMOVE_FILE_FAILD = "REMOVE_FILE_FAILD";

//دانلود فایل
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_FAILD = "DOWNLOAD_FILE_FAILD";

//لیست انواع درخواست
export const LIST_REQUSET_TYPE = "LIST_REQUSET_TYPE";
export const LIST_REQUSET_TYPE_SUCCESS = "LIST_REQUSET_TYPE_SUCCESS";
export const LIST_REQUSET_TYPE_FAILD = "LIST_REQUSET_TYPE_FAILD";

//ایجاد درخواست
export const ADD_REQUSET_TYPE = "ADD_REQUSET_TYPE";
export const ADD_REQUSET_TYPE_SUCCESS = "ADD_REQUSET_TYPE_SUCCESS";
export const ADD_REQUSET_TYPE_FAILD = "ADD_REQUSET_TYPE_FAILD";

//لیست درخواست ها
export const LIST_REQUEST_GRID = "LIST_REQUEST_GRID";
export const LIST_REQUEST_GRID_SUCCESS = "LIST_REQUEST_GRID_SUCCESS";
export const LIST_REQUEST_GRID_FAILD = "LIST_REQUEST_GRID_FAILD";
//لیست درخواست ها بریا فیلترها
export const LIST_REQUSET_TYPE_FOR_FILTER = "LIST_REQUSET_TYPE_FOR_FILTER";
export const LIST_REQUSET_TYPE_FOR_FILTER_SUCCESS = "LIST_REQUSET_TYPE_FOR_FILTER_SUCCESS";
export const LIST_REQUSET_TYPE_FOR_FILTER_FAILD = "LIST_REQUSET_TYPE_FOR_FILTER_FAILD";
//لیست محل فعایت ارزیاب
export const APPLICANT_WORKING_LOCATION_LIST = "APPLICANT_WORKING_LOCATION_LIST";
export const APPLICANT_WORKING_LOCATION_LIST_SUCCESS = "APPLICANT_WORKING_LOCATION_LIST_SUCCESS";
export const APPLICANT_WORKING_LOCATION_LIST_FAILD = "APPLICANT_WORKING_LOCATION_LIST_FAILD";
//لیست سمت های ارزیاب
export const APPLICANT_POSITON_LIST = "APPLICANT_POSITON_LIST";
export const APPLICANT_POSITON_LIST_SUCCESS = "APPLICANT_POSITON_LIST_SUCCESS";
export const APPLICANT_POSITON_LIST_FAILD = "APPLICANT_POSITON_LIST_FAILD";
//تغییر رئیس هیئت مدیره
export const APPLICANT_CURRENT_BOARD_BOSS = "APPLICANT_CURRENT_BOARD_BOSS";
export const APPLICANT_CURRENT_BOARD_BOSS_SUCCESS = "APPLICANT_CURRENT_BOARD_BOSS_SUCCESS";
export const APPLICANT_CURRENT_BOARD_BOSS_FAILD = "APPLICANT_CURRENT_BOARD_BOSS_FAILD";

//لیست درخواست های هر ارزیاب
export const LIST_MY_REQUEST_GRID = "LIST_MY_REQUEST_GRID";
export const LIST_MY_REQUEST_GRID_SUCCESS = "LIST_MY_REQUEST_GRID_SUCCESS";
export const LIST_MY_REQUEST_GRID_FAILD = "LIST_MY_REQUEST_GRID_FAILD";

//لیست درخواست های کارشناس
export const LIST_REQUEST_EXPORT_AWAIT_GRID = "LIST_REQUEST_EXPORT_AWAIT_GRID";
export const LIST_REQUEST_EXPORT_AWAIT_GRID_SUCCESS =
  "LIST_REQUEST_EXPORT_AWAIT_GRID_SUCCESS";
export const LIST_REQUEST_EXPORT_AWAIT_GRID_FAILD =
  "LIST_REQUEST_EXPORT_AWAIT_GRID_FAILD";

//لیست درخواست های رییس
export const LIST_REQUEST_BOSS_AWAIT_GRID = "LIST_REQUEST_BOSS_AWAIT_GRID";
export const LIST_REQUEST_BOSS_AWAIT_GRID_SUCCESS =
  "LIST_REQUEST_BOSS_AWAIT_GRID_SUCCESS";
export const LIST_REQUEST_BOSS_AWAIT_GRID_FAILD =
  "LIST_REQUEST_BOSS_AWAIT_GRID_FAILD";

//تعیین کننده توسط رییس
export const BOSS_DETERMIN = "BOSS_DETERMIN";
export const BOSS_DETERMIN_SUCCESS = "BOSS_DETERMIN_SUCCESS";
export const BOSS_DETERMIN_FAILD = "BOSS_DETERMIN_FAILD";

//تعیین کننده توسط کارشناس
export const EXPERT_DETERMIN = "EXPERT_DETERMIN";
export const EXPERT_DETERMIN_SUCCESS = "EXPERT_DETERMIN_SUCCESS";
export const EXPERT_DETERMIN_FAILD = "EXPERT_DETERMIN_FAILD";

//توضیحات درخواست
export const ADD_DESCRIPTION = "ADD_DESCRIPTION";
export const ADD_DESCRIPTION_SUCCESS = "ADD_DESCRIPTION_SUCCESS";
export const ADD_DESCRIPTION_FAILD = "ADD_DESCRIPTION_FAILD";

//لیسا اعضای هیئت مدیره فعلی
export const CURRENT_BOARD_MEMBER_LIST = "CURRENT_BOARD_MEMBER_LIST";
export const CURRENT_BOARD_MEMBER_LIST_SUCCESS =
  "CURRENT_BOARD_MEMBER_LIST_SUCCESS";
export const CURRENT_BOARD_MEMBER_LIST_FAILD =
  "CURRENT_BOARD_MEMBER_LIST_FAILD ";

//آپدیت تاریخ پایان اعضای هئیت مدیره فعلی
export const BOARD_MEMBER_END_DATE = "BOARD_MEMBER_END_DATE";
export const BOARD_MEMBER_END_DATE_SUCCESS = "BOARD_MEMBER_END_DATE_SUCCESS";
export const BOARD_MEMBER_END_DATE_FAILD = "BOARD_MEMBER_END_DATE_FAILD ";

//لیست اعضای هئیت مدیره جدید
export const NEW_BOARD_MEMBER_LIST = "NEW_BOARD_MEMBER_LIST";
export const NEW_BOARD_MEMBER_LIST_SUCCESS = "NEW_BOARD_MEMBER_LIST_SUCCESS";
export const NEW_BOARD_MEMBER_LIST_FAILD = "NEW_BOARD_MEMBER_LIST_FAILD ";

// اضافه کردن هئیت مدیره جدید
export const ADD_BOARD_MEMBER = "ADD_BOARD_MEMBER";
export const ADD_BOARD_MEMBER_SUCCESS = "ADD_BOARD_MEMBER_SUCCESS";
export const ADD_BOARD_MEMBER_FAILD = "ADD_BOARD_MEMBER_FAILD ";

//لیست نام ارزیابان
export const ADJUSTER_LIST = "ADJUSTER_LIST";
export const ADJUSTER_LIST_SUCCESS = "ADJUSTER_LIST_SUCCESS";
export const ADJUSTER_LIST_FAILD = "ADJUSTER_LIST_SUCCESS ";

//اعضای هئیت مدیره بررسی شده
export const BOARD_MEMBER_REVIEWED = "BOARD_MEMBER_REVIEWED";
export const BOARD_MEMBER_REVIEWED_SUCCESS = "BOARD_MEMBER_REVIEWED_SUCCESS";
export const BOARD_MEMBER_REVIEWED_FAILD = "BOARD_MEMBER_REVIEWED_FAILD";

//اعضای هئیت مدیره بررسی نشده
export const BOARD_MEMBER_NOT_REVIEWED = "BOARD_MEMBER_NOT_REVIEWED";
export const BOARD_MEMBER_NOT_REVIEWED_SUCCESS =
  "BOARD_MEMBER_NOT_REVIEWED_SUCCESS";
export const BOARD_MEMBER_NOT_REVIEWED_FAILD =
  "BOARD_MEMBER_NOT_REVIEWED_FAILD";

//حذف عضو هئیت مدیره
export const DELET_BOARED_MEMBER = "DELET_BOARED_MEMBER";
export const DELET_BOARED_MEMBER_SUCCESS = "DELET_BOARED_MEMBER_SUCCESS";
export const DELET_BOARED_MEMBER_FAILD = "DELET_BOARED_MEMBER_FAILD";

//جزئیات هئیت مدیره
export const DETAIL_BOARED_MEMBER = "DETAIL_BOARED_MEMBER";
export const DETAIL_BOARED_MEMBER_SUCCESS = "DETAIL_BOARED_MEMBER_SUCCESS";
export const DETAIL_BOARED_MEMBER_FAILD = "DETAIL_BOARED_MEMBER_FAILD";

//جزئیات مدیر عامل فعلی
export const APPLICANT_CURRENT_CEO_INFO = "APPLICANT_CURRENT_CEO_INFO";
export const APPLICANT_CURRENT_CEO_INFO_SUCCESS = "APPLICANT_CURRENT_CEO_INFO_SUCCESS";
export const APPLICANT_CURRENT_CEO_INFO_FAILD = "APPLICANT_CURRENT_CEO_INFO_FAILD";
//جزئیات رئیس هیئت مدیره فعلی
export const APPLICANT_BOARD_MEMBER_DEPUTY = "APPLICANT_BOARD_MEMBER_DEPUTY";
export const APPLICANT_BOARD_MEMBER_DEPUTY_SUCCESS = "APPLICANT_BOARD_MEMBER_DEPUTY_SUCCESS";
export const APPLICANT_BOARD_MEMBER_DEPUTY_FAILD = "APPLICANT_BOARD_MEMBER_DEPUTY_FAILD";

//جستجوی ارزیاب
export const APPLICANT_SEARCH_ADJUSTER = "APPLICANT_SEARCH_ADJUSTER";
export const APPLICANT_SEARCH_ADJUSTER_SUCCESS = "APPLICANT_SEARCH_ADJUSTER_SUCCESS";
export const APPLICANT_SEARCH_ADJUSTER_FAILD = "APPLICANT_SEARCH_ADJUSTER_FAILD";

//اسناد
export const DOCUMENT_LIST = "DOCUMENT_LIST";
export const DOCUMENT_LIST_SUCCESS = "DOCUMENT_LIST_SUCCESS";
export const DOCUMENT_LIST_FAILD = "DOCUMENT_LIST_FAILD";

//اضافه کردن اسناد
export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS";
export const ADD_DOCUMENT_FAILD = "ADD_DOCUMENT_FAILD";

//دانلود اسناد
export const DL_DOCUMENT = "DL_DOCUMENT";
export const DL_DOCUMENT_SUCCESS = "DL_DOCUMENT_SUCCESS";
export const DL_DOCUMENT_FAILD = "DL_DOCUMENT_FAILD";

//تاسیس شعبه
export const ADD_ESTABLISHMENT_BRANCH = "ESTABLISHMENT_BRANCH";
export const ADD_ESTABLISHMENT_BRANCH_SUCCESS =
  "ADD_ESTABLISHMENT_BRANCH_SUCCESS";
export const ADD_ESTABLISHMENT_BRANCH_FAILD = "ADD_ESTABLISHMENT_BRANCH_FAILD";

//تغییر محل فعالیت
export const ADD_CHANGE_WORK_LOCATION = "ADD_CHANGE_WORK_LOCATION";
export const ADD_CHANGE_WORK_LOCATION_SUCCESS =
  "ADD_CHANGE_WORK_LOCATION_SUCCESS";
export const ADD_CHANGE_WORK_LOCATION_FAILD = "ADD_CHANGE_WORK_LOCATION_FAILD";

//محل فعالیت
export const LIST_WORK_LOCATION_REQUEST = "LIST_WORK_LOCATION_REQUEST";
export const LIST_WORK_LOCATION_REQUEST_SUCCESS =
  "LIST_WORK_LOCATION_REQUEST_SUCCESS";
export const LIST_WORK_LOCATION_REQUEST_FAILD =
  "LIST_WORK_LOCATION_REQUEST_FAILD";

//ایجاد پیام
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILD = "CREATE_MESSAGE_FAILD";

//لیست پیام ها
export const MESSAGE_GET_GRID = "MESSAGE_GET_GRID";
export const MESSAGE_GET_GRID_SUCCESS = "MESSAGE_GET_GRID_SUCCESS";
export const MESSAGE_GET_GRID_FAILD = "MESSAGE_GET_GRID_FAILD";

//لیست پیام های من
export const MY_MESSAGE_GET_GRID = "MY_MESSAGE_GET_GRID";
export const MY_MESSAGE_GET_GRID_SUCCESS = "MY_MESSAGE_GET_GRID_SUCCESS";
export const MY_MESSAGE_GET_GRID_FAILD = "MY_MESSAGE_GET_GRID_FAILD";


//ایجاد ثبت عملکرد
export const ADD_MONTHLY_PERFORMANCE = "ADD_MONTHLY_PERFORMANCE";
export const ADD_MONTHLY_PERFORMANCE_SUCCESS =
  "ADD_MONTHLY_PERFORMANCE_SUCCESS";
export const ADD_MONTHLY_PERFORMANCE_FAILD = "ADD_MONTHLY_PERFORMANCE_FAILD";

//مشاهده عملکرد
export const VIEW_MONTHLY_PERFORMANCE = "VIEW_MONTHLY_PERFORMANCE";
export const VIEW_MONTHLY_PERFORMANCE_SUCCESS =
  "VIEW_MONTHLY_PERFORMANCE_SUCCESS";
export const VIEW_MONTHLY_PERFORMANCE_FAILD = "VIEW_MONTHLY_PERFORMANCE_FAILD";

//حذف عملکرد
export const Remove_MONTHLY_PERFORMANCE = "Remove_MONTHLY_PERFORMANCE";
export const Remove_MONTHLY_PERFORMANCE_SUCCESS =
  "Remove_MONTHLY_PERFORMANCE_SUCCESS";
export const Remove_MONTHLY_PERFORMANCE_FAILD = "Remove_MONTHLY_PERFORMANCE_FAILD";

// مشاهده عملکردهای من
export const VIEW_MY_MONTHLY_PERFORMANCE = "VIEW_MY_MONTHLY_PERFORMANCE";
export const VIEW_MY_MONTHLY_PERFORMANCE_SUCCESS =
  "VIEW_MY_MONTHLY_PERFORMANCE_SUCCESS";
export const VIEW_MY_MONTHLY_PERFORMANCE_FAILD =
  "VIEW_MY_MONTHLY_PERFORMANCE_FAILD";

//هر عملکرد
export const MONTHLY_PERFORMANCE_ID = "MONTHLY_PERFORMANCE_ID";
export const MONTHLY_PERFORMANCE_ID_SUCCESS = "MONTHLY_PERFORMANCE_ID_SUCCESS";
export const MONTHLY_PERFORMANCE_ID_FAILD = "MONTHLY_PERFORMANCE_ID_FAILD";

//ویرایش هر عملکرد
export const EDIT_MONTHLY_PERFORMANCE = "EDIT_MONTHLY_PERFORMANCE";
export const EDIT_MONTHLY_PERFORMANCE_SUCCESS =
  "EDIT_MONTHLY_PERFORMANCE_SUCCESS";
export const EDIT_MONTHLY_PERFORMANCE_FAILD = "EDIT_CONTRACTEVALUATION_FAILD";

//تغییر استیت درخواست
export const APPLICANTREQUEST_DETERMINE = "APPLICANTREQUEST_DETERMINE";
export const APPLICANTREQUEST_DETERMINE_SUCCESS =
  "APPLICANTREQUEST_DETERMINE_SUCCESS";
export const APPLICANTREQUEST_DETERMINE_FAILD =
  "APPLICANTREQUEST_DETERMINE_FAILD";

//ایجاد ثبت قرارداد
export const ADD_CONTRACTEVALUATION = "ADD_CONTRACTEVALUATION";
export const ADD_CONTRACTEVALUATION_SUCCESS = "ADD_CONTRACTEVALUATION_SUCCESS";
export const ADD_CONTRACTEVALUATION_FAILD = "ADD_CONTRACTEVALUATION_FAILD";

//مشاهده قراردادهای من
export const VIEW_MY_CONTRACTEVALUATION = "VIEW_MY_CONTRACTEVALUATION";
export const VIEW_MY_CONTRACTEVALUATION_SUCCESS =
  "VIEW_MY_CONTRACTEVALUATION_SUCCESS";
export const VIEW_MY_CONTRACTEVALUATION_FAILD =
  "VIEW_MY_CONTRACTEVALUATION_FAILD";

//مشاهده قرارداد
export const VIEW_CONTRACTEVALUATION = "VIEW_CONTRACTEVALUATION";
export const VIEW_CONTRACTEVALUATION_SUCCESS =
  "VIEW_CONTRACTEVALUATION_SUCCESS";
export const VIEW_CONTRACTEVALUATION_FAILD = "VIEW_CONTRACTEVALUATION_FAILD";

//ویرایش ثبت قرارداد
export const EDIT_CONTRACTEVALUATION = "EDIT_CONTRACTEVALUATION";
export const EDIT_CONTRACTEVALUATION_SUCCESS =
  "EDIT_CONTRACTEVALUATION_SUCCESS";
export const EDIT_CONTRACTEVALUATION_FAILD = "EDIT_CONTRACTEVALUATION_FAILD";
//حذف ثبت قرارداد

  
export const REMOVE_CONTRACTEVALUATION = "REMOVE_CONTRACTEVALUATION";
export const REMOVE_CONTRACTEVALUATION_SUCCESS =
  "REMOVE_CONTRACTEVALUATION_SUCCESS";
export const REMOVE_CONTRACTEVALUATION_FAILD = "REMOVE_CONTRACTEVALUATION_FAILD";

//هر قرارداد
export const CONTRACTEVALUATION_ID = "CONTRACTEVALUATION_ID";
export const CONTRACTEVALUATION_ID_SUCCESS = "CONTRACTEVALUATION_ID_SUCCESS";
export const CONTRACTEVALUATION_ID_FAILD = "CONTRACTEVALUATION_ID_FAILD";

//ایجاد کارکنان
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILD = "ADD_EMPLOYEE_FAILD";

//مشاهده کارکنان
export const VIEW_EMPLOYEE = "VIEW_EMPLOYEE";
export const VIEW_EMPLOYEE_SUCCESS = "VIEW_EMPLOYEE_SUCCESS";
export const VIEW_EMPLOYEE_FAILD = "VIEW_EMPLOYEE_FAILD";

//مشاهده هر کارمند
export const VIEW_MY_EMPLOYEE = "VIEW_MY_EMPLOYEE";
export const VIEW_MY_EMPLOYEE_SUCCESS = "VIEW_MY_EMPLOYEE_SUCCESS";
export const VIEW_MY_EMPLOYEE_FAILD = "VIEW_MY_EMPLOYEE_FAILD";

//عضو کارکنان
export const EMPLOYEE_ID = "EMPLOYEE_ID";
export const EMPLOYEE_ID_SUCCESS = "EMPLOYEE_ID_SUCCESS";
export const EMPLOYEE_ID_FAILD = "EMPLOYEE_ID_FAILD";
//گزارش نظارت
export const VIEW_MONITORING_REPORT = "VIEW_MONITORING_REPORT";
export const VIEW_MONITORING_REPORT_SUCCESS = "VIEW_MONITORING_REPORT_SUCCESS";
export const VIEW_MONITORING_REPORT_FAILD = "VIEW_MONITORING_REPORT_FAILD";

//ویرایش کارکنان
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILD = "EDIT_EMPLOYEE_FAILD";

export const REMOVE_FILES = "REMOVE_FILES"