//Draft Judical NewId
export const JUDICAL_NEW_ID = "JUDICAL_NEW_ID";
export const JUDICAL_NEW_ID_SUCCESS = "JUDICAL_NEW_ID_SUCCESS";
export const JUDICAL_NEW_ID_FAILD = "JUDICAL_NEW_ID_FAILD";

//Draft Judical  PersonalInfo
export const JUDICAL_DRAFT_PERSONAL_INFO = "JUDICAL_DRAFT_PERSONAL_INFO";
export const JUDICAL_DRAFT_PERSONAL_INFO_SUCCESS =
  "JUDICAL_DRAFT_PERSONAL_INFO_SUCCESS";
export const JUDICAL_DRAFT_PERSONAL_INFO_FAILD =
  "JUDICAL_DRAFT_PERSONAL_INFO_FAILD";

//draft judicial get all info for edit
export const JUDICIAL_DRAFT_GET_PERSONAL_INFO =
  "JUDICIAL_DRAFT_GET_PERSONAL_INFO";
export const JUDICIAL_DRAFT_GET_PERSONAL_INFO_SUCCESS =
  "JUDICIAL_DRAFT_GET_PERSONAL_INFO_SUCCESS";
export const JUDICIAL_DRAFT_GET_PERSONAL_INFO_FAILD =
  "JUDICIAL_DRAFT_GET_PERSONAL_INFO_FAILD";

//Draft Judical NationalIdentity
export const JUDICAL_DRAFT_NATIONAL_IDENTIFY =
  "JUDICAL_DRAFT_NATIONAL_IDENTIFY";
export const JUDICAL_DRAFT_NATIONAL_IDENTIFY_SUCCESS =
  "JUDICAL_DRAFT_NATIONAL_IDENTIFY_SUCCESS";
export const JUDICAL_DRAFT_NATIONAL_IDENTIFY_FAILD =
  "JUDICAL_DRAFT_NATIONAL_IDENTIFY_FAILD";

//Draft Judical Add FamilyMember
export const JUDICAL_DRAFT_ADD_FAMILY_MEMBER =
  "JUDICAL_DRAFT_ADD_FAMILY_MEMBER";
export const JUDICAL_DRAFT_ADD_FAMILY_MEMBER_SUCCESS =
  "JUDICAL_DRAFT_ADD_FAMILY_MEMBER_SUCCESS";
export const JUDICAL_DRAFT_ADD_FAMILY_MEMBER_FAILD =
  "JUDICAL_DRAFT_ADD_FAMILY_MEMBER_FAILD";

//Draft Judical ALL FamilyMember
export const ALL_JUDICAL_DRAFT_FAMILY_MEMBER =
  "ALL_JUDICAL_DRAFT_FAMILY_MEMBER";
export const ALL_JUDICAL_DRAFT_FAMILY_MEMBER_SUCCESS =
  "ALL_JUDICAL_DRAFT_FAMILY_MEMBER_SUCCESS";
export const ALL_JUDICAL_DRAFT_FAMILY_MEMBER_FAILD =
  "ALL_JUDICAL_DRAFT_FAMILY_MEMBER_FAILD";

//Draft Judical Delet FamilyMember
export const JUDICAL_DRAFT_DELET_FAMILY_MEMBER =
  "JUDICAL_DRAFT_DELET_FAMILY_MEMBER";
export const JUDICAL_DRAFT_DELET_FAMILY_MEMBER_SUCCESS =
  "JUDICAL_DRAFT_DELET_FAMILY_MEMBER_SUCCESS";
export const JUDICAL_DRAFT_DELET_FAMILY_MEMBER_FAILD =
  "JUDICAL_DRAFT_DELET_FAMILY_MEMBER_FAILD";

// Draft Judical FeildInfo
export const JUDICAL_DRAFT_FEILD_INFO = "JUDICAL_DRAFT_FEILD_INFO";
export const JUDICAL_DRAFT_FEILD_INFO_SUCCESS =
  "JUDICAL_DRAFT_FEILD_INFO_SUCCESS";
export const JUDICAL_DRAFT_FEILD_INFO_FAILD = "JUDICAL_DRAFT_FEILD_INFO_FAILD";

//Draft Judical Inquire80hourCertificate
export const JUDICAL_DRAFT_INQUIRE_CERTIFICATE80 =
  "JUDICAL_DRAFT_INQUIRE_CERTIFICATE80";
export const JUDICAL_DRAFT_INQUIRE_CERTIFICATE80_SUCCESS =
  "JUDICAL_DRAFT_INQUIRE_CERTIFICATE80_SUCCESS";
export const JUDICAL_DRAFT_INQUIRE_CERTIFICATE80_FAILD =
  "JUDICAL_DRAFT_INQUIRE_CERTIFICATE80_FAILD";

//Draft Judical WorkPlace
export const JUDICAL_DRAFT_WORK_PLACE = "JUDICAL_DRAFT_WORK_PLACE";
export const JUDICAL_DRAFT_WORK_PLACE_SUCCESS =
  "JUDICAL_DRAFT_WORK_PLACE_SUCCESS";
export const JUDICAL_DRAFT_WORK_PLACE_FAILD = "JUDICAL_DRAFT_WORK_PLACE_FAILD";

/**
 * WORKEXPERIENCE
 */
//Draft Judical  AddWorkeExperience
export const JUDICAL_DRAFT_ADD_WORK_EXPERIENCE =
  "JUDICAL_DRAFT_ADD_WORK_EXPERIENCE";
export const JUDICAL_DRAFT_ADD_WORK_EXPERIENCE_SUCCESS =
  "JUDICAL_DRAFT_ADD_WORK_EXPERIENCE_SUCCESS";
export const JUDICAL_DRAFT_ADD_WORK_EXPERIENCE_FAILD =
  "JUDICAL_DRAFT_ADD_WORK_EXPERIENCE_FAILD";

//Draft Judical LISTWorkeExperience
export const LIST_JUDICAL_DRAFT_WORK_EXPERIENCE =
  "LIST_JUDICAL_DRAFT_WORK_EXPERIENCE";
export const LIST_JUDICAL_DRAFT_WORK_EXPERIENCE_SUCCESS =
  "LIST_JUDICAL_DRAFT_WORK_EXPERIENCE_SUCCESS";
export const LIST_JUDICAL_DRAFT_WORK_EXPERIENCE_FAILD =
  "LIST_JUDICAL_DRAFT_WORK_EXPERIENCE_FAILD";

//Draft Judical DELET WorkeExperience
export const DELET_JUDICAL_DRAFT_WORK_EXPERIENCE =
  "DELET_JUDICAL_DRAFT_WORK_EXPERIENCE";
export const DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_SUCCESS =
  "DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_SUCCESS";
export const DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_FAILD =
  "DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_FAILD";

//Draft judical Upload WorkeExperienceCertificate
export const UPLOAD_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "UPLOAD_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const UPLOAD_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "UPLOAD_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const UPLOAD_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "UPLOAD_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

//Draft judical Work Experience get info to make user to be able to edit
export const JUDICIAL_DRAFT_GET_WORK_LOCATION_INFO =
  "JUDICIAL_DRAFT_GET_WORK_LOCATION_INFO";
export const JUDICIAL_DRAFT_GET_WORK_LOCATION_INFO_SUCCESS =
  "JUDICIAL_DRAFT_GET_WORK_LOCATION_INFO_SUCCESS";
export const JUDICIAL_DRAFT_GET_WORK_LOCATION_INFO_FAILD =
  "JUDICIAL_DRAFT_GET_WORK_LOCATION_INFO_FAILD";

//Draft judical Remove WorkExperinceCertificate
export const DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "DELET_JUDICAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

//upload profilePic
export const UPLOAD_JUDICAL_DRAFT_PERSONAL_INFO_PIC =
  "UPLOAD_JUDICAL_DRAFT_PERSONAL_INFO_PIC";
export const UPLOAD_JUDICAL_DRAFT_PERSONAL_INFO_PIC_SUCCESS =
  "UPLOAD_JUDICAL_DRAFT_PERSONAL_INFO_PIC_SUCCESS";
export const UPLOAD_JUDICAL_DRAFT_PERSONAL_INFO_PIC_FAILD =
  "UPLOAD_JUDICAL_DRAFT_PERSONAL_INFO_PIC_FAILD";

export const GET_JUDICAL_DRAFT_PERSONAL_INFO_PIC =
  "GET_JUDICAL_DRAFT_PERSONAL_INFO_PIC";
export const GET_JUDICAL_DRAFT_PERSONAL_INFO_PIC_SUCCESS =
  "GET_JUDICAL_DRAFT_PERSONAL_INFO_PIC_SUCCESS";
export const GET_JUDICAL_DRAFT_PERSONAL_INFO_PIC_FAILD =
  "GET_JUDICAL_DRAFT_PERSONAL_INFO_PIC_FAILD";

//disable next button work experience
export const JUDICIAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_TRUE =
  "JUDICIAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_TRUE";
export const JUDICIAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_FALSE =
  "JUDICIAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_FALSE";

//get main personal info to edit
export const JUDICIAL_PERSONAL_INFO = "JUDICIAL_PERSONAL_INFO";
export const JUDICIAL_PERSONAL_INFO_SUCCESS = "JUDICIAL_PERSONAL_INFO_SUCCESS";
export const JUDICIAL_PERSONAL_INFO_FAILED = "JUDICIAL_PERSONAL_INFO_FAILED";

// get main adjustment field info
export const JUDICAL_GET_FIELD_INFO = "JUDICAL_GET_FIELD_INFO";
export const JUDICAL_GET_FIELD_INFO_SUCCESS = "JUDICAL_GET_FIELD_INFO_SUCCESS";
export const JUDICAL_GET_FIELD_INFO_FAILD = "JUDICAL_GET_FIELD_INFO_FAILD";

export const GET_BIRTH_CITY_PROVINCE_ID = "GET_BIRTH_CITY_PROVINCE_ID";
export const GET_BIRTH_CITY_PROVINCE_ID_SUCCESS =
  "GET_BIRTH_CITY_PROVINCE_ID_SUCCESS";
export const GET_BIRTH_CITY_PROVINCE_ID_FAILED =
  "GET_BIRTH_CITY_PROVINCE_ID_FAILED";

export const GET_RESIDENCE_CITY_PROVINCE_ID = "GET_RESIDENCE_CITY_PROVINCE_ID";
export const GET_RESIDENCE_CITY_PROVINCE_ID_SUCCESS =
  "GET_RESIDENCE_CITY_PROVINCE_ID_SUCCESS";
export const GET_RESIDENCE_CITY_PROVINCE_ID_FAILED =
  "GET_RESIDENCE_CITY_PROVINCE_ID_FAILED";

export const GET_WORK_CITY_PROVINCE_ID = "GET_WORK_CITY_PROVINCE_ID";
export const GET_WORK_CITY_PROVINCE_ID_SUCCESS =
  "GET_WORK_CITY_PROVINCE_ID_SUCCESS";
export const GET_WORK_CITY_PROVINCE_ID_FAILED =
  "GET_WORK_CITY_PROVINCE_ID_FAILED";

export const GET_SUB_FIELD_BASED_ON_FIELD_JUDICIAL =
  "GET_SUB_FIELD_BASED_ON_FIELD_JUDICIAL";
export const GET_SUB_FIELD_BASED_ON_FIELD_JUDICIAL_SUCCESS =
  "GET_SUB_FIELD_BASED_ON_FIELD_JUDICIAL_SUCCESS";
export const GET_SUB_FIELD_BASED_ON_FIELD_JUDICIAL_FAILED =
  "GET_SUB_FIELD_BASED_ON_FIELD_JUDICIAL_FAILED";

export const LEGAL_IS_EXAM_NOT_NEEDED_TRUE = "LEGAL_IS_EXAM_NOT_NEEDED_TRUE";
export const LEGAL_IS_EXAM_NOT_NEEDED_FALSE = "LEGAL_IS_EXAM_NOT_NEEDED_FALSE";

export const JUDICIAL_DRAFT_INQUIRE_FIELD_CERTIFICATE =
  "JUDICIAL_DRAFT_INQUIRE_FIELD_CERTIFICATE";
export const JUDICIAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_SUCCESS =
  "JUDICIAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_SUCCESS";
export const JUDICIAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_FAILD =
  "JUDICIAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_FAILD";

export const IS_SUBFIELD_INQUIRED_JUDICIAL_ADD =
  "IS_SUBFIELD_INQUIRED_JUDICIAL_ADD";
export const IS_SUBFIELD_INQUIRED_JUDICIAL_REMOVE =
  "IS_SUBFIELD_INQUIRED_JUDICIAL_REMOVE";

export const GET_SELECTED_FIELD_INFO_NATURAL =
  "GET_SELECTED_FIELD_INFO_NATURAL";
export const GET_SELECTED_FIELD_INFO_NATURAL_SUCCESS =
  "GET_SELECTED_FIELD_INFO_NATURAL_SUCCESS";
export const GET_SELECTED_FIELD_INFO_NATURAL_FAILED =
  "GET_SELECTED_FIELD_INFO_NATURAL_FAILED";

export const GET_JUDICAL_EDIT_FEILD_INFO = "GET_JUDICAL_EDIT_FEILD_INFO";
export const GET_JUDICAL_EDIT_FEILD_INFO_SUCCESS =
  "GET_JUDICAL_EDIT_FEILD_INFO_SUCCESS";
export const GET_JUDICAL_EDIT_FEILD_INFO_FAILED =
  "GET_JUDICAL_EDIT_FEILD_INFO_FAILED";

export const GET_BIRTHDAY_CITY_PROVINCE_ID =
  "GET_BIRTHDAY_CITY_PROVINCE_ID";
export const GET_BIRTHDAY_CITY_PROVINCE_ID_SUCCESS =
  "GET_BIRTHDAY_CITY_PROVINCE_ID_SUCCESS";
export const GET_BIRTHDAY_CITY_PROVINCE_ID_FAILED =
  "GET_BIRTHDAY_CITY_PROVINCE_ID_FAILED";
