export enum userAccessList {
  Adjusters_CreateCourse = 25001, // ایجاد دوره
  Adjusters_ViewCourses = 25002, //مشاهده لیست دوره ها
  Adjusters_EditCourse = 25003, //ویرایش دوره
  Adjusters_DeleteCourse = 25004, // حذف دوره
  Adjusters_CreateInterviewTiming = 25005, //ایجاد زمان مصاحبه
  Adjusters_CreateInterviewer = 25006, //ایجاد مصاحبه کننده
  Adjusters_EditInterviewer = 25007, //ویرایش مصاحبه کننده
  Adjusters_DeleteInterviewer = 25008, //حذف مصاحبه کننده
  Adjusters_ViewInterviwers = 25009, //مصاحبه کننده ها
  Adjusters_CreateDocumentType = 25010, //ایجادنوع مدرک
  Adjusters_ViewDocumentType = 25011, //دیدن مدارک
  Adjusters_EditDocumentType = 25012, //ویرایش مدارک
  Adjusters_DeleteDocumentType = 25013, // حذف مدارک
  Adjusters_CreateAdjustmentField = 25014, // ایجاد رشته تخصصی
  Adjusters_ViewAdjustmentFiled = 25015, //مشاهده رشته تخصصی
  Adjusters_EditAdjustmentField = 25016, // ویرایش رشته تخصصی
  Adjusters_DeleteAdjustmentField = 25017, // حذف رشته تخصصی
  Adjusters_CreateRejectReason = 25018, //ایجاد دلایل رد
  Adjusters_ViewRejectReason = 25019, // مشاهده دلایل رد
  Adjusters_EditRejectReason = 25020, // ویرایش دلایل رد
  Adjusters_DeleteRejectReason = 25021, // حذف دلایل رد
  Adjusters_CreateChangeStatusReason = 25022, // ایجاد دلایل تغییر وضعیت
  Adjusters_ViewChangeStatusReason = 25023, // مشاهده دلایل تغییر وضعیت
  Adjusters_EditChangeStatusReason = 25024, //ویرایش دلایل تغییر وضعیت
  Adjusters_DeleteChangeStatusReason = 25025, //حذف دلایل تغییر وضعیت
  Adjusters_CreateActor = 25026, //ایجاد کاربر
  Adjusters_ViewActor = 25027, //مشاهده کاربران
  Adjusters_EditActor = 25028, //ویرایش کاربران
  Adjusters_DeleteActor = 25029, //حذف کاربران
  Adjusters_AssignIncommingAdjuster = 25030, //ارجاع پرونده های اولیه
  Adjusters_Cartable = 25031, //مشاهده کارتابل
  Adjusters_ViewLicense = 25032, //مشاهده پروانه
  Adjusters_LicenseIssue = 25033, //صدور کد ارزیابی
  Adjusters_ViewChargoonLetter = 25034, //مشاهده نامه چارگون
  Adjusters_DocumentInformation = 25035, //مشاهده اطلاعات پرونده
  Adjusters_DocumentDetail = 25036, //جزییات پرونده
  Adjusters_CreateInterviewScore = 25037, //ایجاد نمره مصاحبه
  Adjusters_EditInterviewScore = 25038, //ویرایش نمره مصاحبه
  Adjusters_DeleteInterviewScore = 25039, //حذف نمره مصاحبه
  Adjusters_InterviewMinutes = 25040, //مشاهده صورتجلسه مصاحبه
  Adjusters_EditApplicantAdjustmentField = 25041, //تغییر رشته ارزیاب
  // Adjusters_SetApplicantInterview = 25042, //ایجاد جلسه مصاحبه
  // Adjusters_EditApplicantInterview = 25043, //ویرایش جلسه مصاحبه
  // Adjusters_DeleteApplicantInterview = 25044, //حدف جلسه مصاحبه
  // Adjusters_SetApplicantInterviewer = 25045, //تنظیم جلسه مصاحبه کننده
  // Adjusters_EditApplicantInterviewer = 25046, //ویرایش جلسه مصاحبه کننده
  // Adjusters_DeleteApplicantInterviewer = 25047, //حذف جلسه مصاحبه کننده
  Adjusters_SendChargoonLetter = 25048, //ارسال نامه چارگون
  Adjusters_SendSms = 25049, //ارسال پیامک
  Adjusters_SendGroupSms = 25050, //ارسال پیامک گروهی
  Adjusters_ViewInterviewInvitationDocument = 25051, //مشاهده پرونده های دعوت به مصاحبه
  Adjusters_ViewReadyToInterviewDocument = 25052, //مشاهده پرونده های آماده به مصاحبه
  Adjusters_ViewFilingDocument = 25053, //مشاهده پرونده های تشکیل پرونده
  Adjusters_CartableReport = 25054, //مشاهده گزارش کارتابل
  Adjusters_SwapCartable = 25055, //تغییر کارشناس
  Adjusters_ViewReport = 25056, //مشاهده گزارشات
  Adjusters_SmsOutBox = 25057, //مشاهده پیامک های ارسالی
  Adjusters_ViewArchiveFiles = 25058, //مشاهده پرونده های بایگانی شده
  Adjusters_ViewRequestCartable = 25059, //مشاهده کارتابل درخواست ها
  Adjusters_ViewRequestDetail = 25060, //مشاهده جزییات درخواست
  Adjusters_DetermineRequest = 25001, //بررسی درخواست ها
  Adjusters_ViewManagementCartable = 25061, //مشاهده کارتابل مدیریت
  Adjusters_SendMessage = 25062, //ارسال پیام
  Adjusters_ViewApplicantStatusHistory = 25063, //مشاهده تاریخچه تغییرات تغییر وضعیت ارزیاب
  Adjusters_ActiveApplicantDesktop = 25064, //فعال کردن میزکار ارزیاب
  Adjusters_ChangeApplicantStatus = 25065, //تغییر وضعیت ارزیاب
  Adjusters_ExtensionLicense = 25066, //تمدید پروانه
  Adjusters_CreateApplicantRequest = 25067, //ایجاد درخواست
  // Adjusters_ApplicantDesktop = 25068, //میزکار ارزیاب
}
