import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css'
import localFont from "next/font/local";

const tanha = localFont({
    src:"./Tanha.woff2",
    display:"swap"
});

export const metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fa-IR" dir="rtl" className={tanha.className}>
            <body>{children}</body>
        </html>
    );
}
