//baseINFO
export const BASE_INFO = "BASE_INFO";
export const BASE_INFO_SUCCESS = "BASE_INFO_SUCCESS";
export const BASE_INFO_FAILD = "BASE_INFO_FAILD";

//inquire
export const INQUIRE = "INQUIRE";
export const INQUIRE_SUCCESS = "INQUIRE_SUCCESS";
export const INQUIRE_FAILD = "INQUIRE_FAILD";

//request document type
export const REQUEST_DOCUMENT_TYPES = "REQUEST_DOCUMENT_TYPES";
export const REQUEST_DOCUMENT_TYPES_SUCCESS = "REQUEST_DOCUMENT_TYPES_SUCCESS";
export const REQUEST_DOCUMENT_TYPES_FAILD = "REQUEST_DOCUMENT_TYPES_FAILD";

//adjuster active report excel
export const ACTIVE_ADJUSTER_EXCEL = "ACTIVE_ADJUSTER_EXCEL"
export const ACTIVE_ADJUSTER_EXCEL_SUCCESS = "ACTIVE_ADJUSTER_EXCEL_SUCCESS"
export const ACTIVE_ADJUSTER_EXCEL_FAILED = "ACTIVE_ADJUSTER_EXCEL_FAILED"
//applicant G4B send message
export const G4B_SEND_MESSAGE = "G4B_SEND_MESSAGE"
export const G4B_SEND_MESSAGE_SUCCESS = "G4B_SEND_MESSAGE_SUCCESS"
export const G4B_SEND_MESSAGE_FAILD = "G4B_SEND_MESSAGE_FAILD"
//applicant G4B check registeration
export const G4B_CHECK_REGISTERATION= "G4B_CHECK_REGISTERATION"
export const G4B_CHECK_REGISTERATION_SUCCESS = "G4B_CHECK_REGISTERATION_SUCCESS"
export const G4B_CHECK_REGISTERATION_FAILD = "G4B_CHECK_REGISTERATION_FAILD"
//applicant G4B document approved
export const G4B_DOCUMENT_APPROVED= "G4B_DOCUMENT_APPROVED"
export const G4B_DOCUMENT_APPROVED_SUCCESS = "G4B_DOCUMENT_APPROVED_SUCCESS"
export const G4B_DOCUMENT_APPROVED_FAILD = "G4B_DOCUMENT_APPROVED_FAILD"
//applicant G4B register
export const G4B_REGISTER= "G4B_REGISTER"
export const G4B_REGISTER_SUCCESS = "G4B_REGISTER_SUCCESS"
export const G4B_REGISTER_FAILD = "G4B_REGISTER_FAILD"

// report active adjusters

export const ACTIVE_ADJUSTERS = "ACTIVE_ADJUSTERS"
export const ACTIVE_ADJUSTERS_SUCCESS = "ACTIVE_ADJUSTERS_SUCCESS"
export const ACTIVE_ADJUSTERS_FAILD = "ACTIVE_ADJUSTERS_FAILD"

//all stafType
export const STAFF_TYPE = "STAFF_TYPE";
export const STAFF_TYPE_SUCCESS = "STAFF_TYPE_SUCCESS";
export const STAFF_TYPE_FAILD = "STAFF_TYPE_FAILD";

//create staff
export const CREATE_STAFF = "CREATE_STAFF";
export const CREATE_STAFF_SUCCESS = "CREATE_STAFF_SUCCESS";
export const CREATE_STAFF_FAILD = "CREATE_STAFF_FAILD";

//search user
export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILD = "SEARCH_USER_FAILD";

// User grid
export const USER_GET_FOR_GRID = "USER_GET_FOR_GRID";
export const USER_GET_FOR_GRID_SUCCESS = "USER_GET_FOR_GRID_SUCCESS";
export const USER_GET_FOR_GRID_FAILD = "USER_GET_FOR_GRID_FAILD";

//remove User
export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILD = "REMOVE_USER_FAILD";

export const NATURAL_PERSON_ALL = "NATURAL_PERSON_ALL";
export const NATURAL_PERSON_ALL_SUCCESS = "NATURAL_PERSON_ALL_SUCCESS";
export const NATURAL_PERSON_ALL_FAILD = "NATURAL_PERSON_ALL_FAILD";


//adjusment parent list
export const ADJUSTMENT_FIELD_PARENT_LIST = "ADJUSTMENT_FIELD_PARENT_LIST";
export const ADJUSTMENT_FIELD_PARENT_LIST_SUCCESS = "ADJUSTMENT_FIELD_PARENT_LIST_SUCCESS";
export const ADJUSTMENT_FIELD_PARENT_LIST_FAILD = "ADJUSTMENT_FIELD_PARENT_LIST_FAILD";


//list Adjuster_Natural_Judical_Personal_list
export const ADJUSTER_NATURAL_JUDICAL_PERSONAL_LIST =
  "ADJUSTER_NATURAL_JUDICAL_PERSONAL_LIST";
export const ADJUSTER_NATURAL_JUDICAL_PERSONAL_LIST_SUCCESS =
  "ADJUSTER_NATURAL_JUDICAL_PERSONAL_LIST_SUCCESS";
export const ADJUSTER_NATURAL_JUDICAL_PERSONAL_LIST_FAILD =
  "ADJUSTER_NATURAL_JUDICAL_PERSONAL_LIST_FAILD";

//Denomination ReligionId
export const DENOMINATION_RELIGION_ID = "DENOMINATION_RELIGION_ID";
export const DENOMINATION_RELIGION_ID_SUCCESS =
  "DENOMINATION_RELIGION_ID_SUCCESS";
export const DENOMINATION_RELIGION_ID_FAILD = "DENOMINATION_RELIGION_ID_FAILD";

//DraftNewId
export const DRAFT_NEWID = "DRAFT_NEWID";
export const DRAFT_NEWID_SUCCESS = "DRAFT_NEWID_SUCCESS";
export const DRAFT_NEWID_FAILD = "DRAFT_NEWID_FAILD";

//LegalNewId
export const LEGAL_NEWID = "LEGAL_NEWID";
export const LEGAL_NEWID_SUCCESS = "LEGAL_NEWID_SUCCESS";
export const LEGAL_NEWID_FAILD = "LEGAL_NEWID_FAILD";


//Draft PersonalInfo
export const DRAFT_PERSONAL_INFO = "DRAFT_PERSONAL_INFO";
export const DRAFT_PERSONAL_INFO_SUCCESS = "DRAFT_PERSONAL_INFO_SUCCESS";
export const DRAFT_PERSONAL_INFO__FAILD = "DRAFT_PERSONAL_INFO_FAILD";

//draft National Identity
export const DRAFT_NATIONAL_IDENTIFY = "DRAFT_NATIONAL_IDENTIFY";
export const DRAFT_NATIONAL_IDENTIFY_SUCCESS =
  "DRAFT_NATIONAL_IDENTIFY_SUCCESS";
export const DRAFT_NATIONAL_IDENTFTY__FAILD = "DRAFT_NATIONAL_IDENTFTY__FAILD";

//Natural Draft FamilyMember
export const DRAFT_NATURAL_FAMILY_MEMBER = "DRAFT_NATURAL_FAMILY_MEMBER";
export const DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS =
  "DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS";
export const DRAFT_FAMILY_MEMBER__FAILD = "DRAFT_FAMILY_MEMBER__FAILD";

//All Natural Draft FamilyMember
export const ALL_DRAFT_NATURAL_FAMILY_MEMBER =
  "ALL_DRAFT_NATURAL_FAMILY_MEMBER";
export const ALL_DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS =
  "ALL_DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS";
export const ALL_DRAFT_NATURAL_FAMILY_MEMBER__FAILD =
  "ALL_DRAFT_NATURAL_FAMILY_MEMBER__FAILD";

//Delet Natural DraftFamilyMember
export const DELET_DRAFT_NATURAL_FAMILY_MEMBER =
  "DELET_DRAFT_NATURAL_FAMILY_MEMBER";
export const DELET_DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS =
  "DELET_DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS";
export const DELET_DRAFT_NATURAL_FAMILY_MEMBER__FAILD =
  "DELET_DRAFT_NATURAL_FAMILY_MEMBER__FAILD";

//Update Natural Draft FamilyMember
export const UPDATE_DRAFT_NATURAL_FAMILY_MEMBER =
  "UPDATE_DRAFT_NATURAL_FAMILY_MEMBER";
export const UPDATE_DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS =
  "UPDATE_DRAFT_NATURAL_FAMILY_MEMBER_SUCCESS";
export const UPDATE_DRAFT_NATURAL_FAMILY_MEMBER__FAILD =
  "UPDATE_DRAFT_NATURAL_FAMILY_MEMBER__FAILD";

//Natural Draft PersonalInfo
export const NATURAL_DRAFT_PERSONAL_INFO = "NATURAL_DRAFT_PERSONAL_INFO";
export const NATURAL_DRAFT_PERSONAL_INFO_SUCCESS =
  "NATURAL_DRAFT_PERSONAL_INFO_SUCCESS";
export const NATURAL_DRAFT_PERSONAL_INFO_FAILD =
  "NATURAL_DRAFT_PERSONAL_INFO_FAILD";

//natural draft get personal info for edit
export const NATURAL_DRAFT_PERSONAL_INFO_GET =
  "NATURAL_DRAFT_PERSONAL_INFO_GET";
export const NATURAL_DRAFT_PERSONAL_INFO_GET_SUCCESS =
  "NATURAL_DRAFT_PERSONAL_INFO_GET_SUCCESS";
export const NATURAL_DRAFT_PERSONAL_INFO_GET_FAILD =
  "NATURAL_DRAFT_PERSONAL_INFO_GET_FAILD";

//Natural Draft FeildInfo
export const NATURAL_DRAFT_FEILD_INFO = "NATURAL_DRAFT_FEILD_INFO";
export const NATURAL_DRAFT_FEILD_INFO_SUCCESS =
  "NATURAL_DRAFT_FEILD_INFO_SUCCESS";
export const NATURAL_DRAFT_FEILD_INFO_FAILD = "NATURAL_DRAFT_FEILD_INFO_FAILD";

//Natural Draft Inquire80hourCertificate
export const NATURAL_DRAFT_INQUIRE_CERTIFICATE =
  "NATURAL_DRAFT_INQUIRE_CERTIFICATE";
export const NATURAL_DRAFT_INQUIRE_CERTIFICATE_SUCCESS =
  "NATURAL_DRAFT_INQUIRE_CERTIFICATE_SUCCESS";
export const NATURAL_DRAFT_INQUIRE_CERTIFICATE_FAILD =
  "NATURAL_DRAFT_INQUIRE_CERTIFICATE_FAILD";

//Natural Draft IinquireField Certificate
export const NATURAL_DRAFT_INQUIRE_FIELD_CERTIFICATE =
  "NATURAL_DRAFT_INQUIRE_FIELD_CERTIFICATE";
export const NATURAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_SUCCESS =
  "NATURAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_SUCCESS";
export const NATURAL_DRAFT_INQUIRE_FIELD_CERTIFICATE_FAILD =
  "NATURAL_DRAFT_INQUIRE_CERTIFICATE_FAILD";

//Natural Draft WorkPlace
export const NATURAL_DRAFT_WORK_PLACE = "NATURAL_DRAFT_WORK_PLACE";
export const NATURAL_DRAFT_WORK_PLACE_SUCCESS =
  "NATURAL_DRAFT_WORK_PLACE_SUCCESS";
export const NATURAL_DRAFT_WORK_PLACE_FAILD = "NATURAL_DRAFT_WORK_PLACE_FAILD";

//Natural Draft WorkeExperience
export const NATURAL_DRAFT_WORK_EXPERIENCE = "NATURAL_DRAFT_WORK_EXPERIENCE";
export const NATURAL_DRAFT_WORK_EXPERIENCE_SUCCESS =
  "NATURAL_DRAFT_WORK_EXPERIENCE_SUCCESS";
export const NATURAL_DRAFT_WORK_EXPERIENCE_FAILD =
  "NATURAL_DRAFT_WORK_EXPERIENCE_FAILD";

//natural draft get work location info for edit
export const NATURAL_DRAFT_WORK_LOCATION_GET =
  "NATURAL_DRAFT_WORK_LOCATION_GET";
export const NATURAL_DRAFT_WORK_LOCATION_GET_SUCCESS =
  "NATURAL_DRAFT_WORK_LOCATION_GET_SUCCESS";
export const NATURAL_DRAFT_WORK_LOCATION_GET_FAILD =
  "NATURAL_DRAFT_WORK_LOCATION_GET_FAILD";

//Natural Draft LIST WorkeExperienceGuid
export const LIST_NATURAL_DRAFT_WORK_EXPERIENCE_GUID =
  "LIST_NATURAL_DRAFT_WORK_EXPERIENCE_GUID";
export const LIST_NATURAL_DRAFT_WORK_EXPERIENCE_GUID_SUCCESS =
  "LIST_NATURAL_DRAFT_WORK_EXPERIENCE_GUID_SUCCESS";
export const LIST_NATURAL_DRAFT_WORK_EXPERIENCE_GUID_FAILD =
  "LIST_NATURAL_DRAFT_WORK_EXPERIENCE_GUID_FAILD";

//Natural Draft Upload Certificate
export const UPLOAD_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "UPLOAD_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const UPLOAD_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "UPLOAD_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const UPLOAD_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "UPLOAD_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

//Natural Draft List WorkExperince Certificate
export const LIST_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "LIST_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const LIST_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "LIST_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const LIST_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "LIST_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

//Natural Draft Remove WorkExperince Certificate
export const DELET_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "DELET_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const DELET_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "DELET_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const DELET_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "DELET_NATURAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

export const DELET_NATURAL_DRAFT_WORK_EXPERIENCE =
  "DELET_NATURAL_DRAFT_WORK_EXPERIENCE ";
export const DELET_NATURAL_DRAFT_WORK_EXPERIENCE_SUCCESS =
  "DELET_NATURAL_DRAFT_WORK_EXPERIENCE_SUCCESS ";
export const DELET_NATURAL_DRAFT_WORK_EXPERIENCE_FAILD =
  "DELET_NATURAL_DRAFT_WORK_EXPERIENCE_FAILD ";

export const UPLOAD_DRAFT_PERSONAL_INFO_PIC = "UPLOAD_DRAFT_PERSONAL_INFO_PIC";
export const UPLOAD_DRAFT_PERSONAL_INFO_PIC_SUCCESS =
  "UPLOAD_DRAFT_PERSONAL_INFO_PIC_SUCCESS";
export const UPLOAD_DRAFT_PERSONAL_INFO_PIC__FAILD =
  "UPLOAD_DRAFT_PERSONAL_INFO_PIC__FAILD";

export const GET_DRAFT_PERSONAL_INFO_PIC = "GET_DRAFT_PERSONAL_INFO_PIC";
export const GET_DRAFT_PERSONAL_INFO_PIC_SUCCESS =
  "GET_DRAFT_PERSONAL_INFO_PIC_SUCCESS";
export const GET_DRAFT_PERSONAL_INFO_PIC_FAILD =
  "GET_DRAFT_PERSONAL_INFO_PIC_FAILD";

export const NATURAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_TRUE =
  "NATURAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_TRUE";
export const NATURAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_FALSE =
  "NATURAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_FALSE";

export const SEND_REFER_NATURAL = "SEND_REFER_NATURAL";
export const SEND_REFER_NATURAL_SUCCESS = "SEND_REFER_NATURAL_SUCCESS";
export const SEND_REFER_NATURAL__FAILD = "SEND_REFER_NATURAL__FAILD";

export const NATURAL_EDIT_FIELD_INFO_GET_SPECIALIZED_FIELD_INFO =
  "NATURAL_EDIT_FIELD_INFO_GET_SPECIALIZED_FIELD_INFO";
export const NATURAL_EDIT_FIELD_INFO_GET_SPECIALIZED_FIELD_INFO_SUCCESS =
  "NATURAL_EDIT_FIELD_INFO_GET_SPECIALIZED_FIELD_INFO_SUCCESS";
export const NATURAL_EDIT_FIELD_INFO_GET_SPECIALIZED_FIELD_INFO_FAILED =
  "NATURAL_EDIT_FIELD_INFO_GET_SPECIALIZED_FIELD_INFO_FAILED";

export const NATURAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO =
  "NATURAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO";
export const NATURAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_SUCCESS =
  "NATURAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_SUCCESS";
export const NATURAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_FAILED =
  "NATURAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_FAILED";

export const DELETE_NATURAL_SPECIALIZED_FIELD_INFO =
  "DELETE_NATURAL_SPECIALIZED_FIELD_INFO";
export const DELETE_NATURAL_SPECIALIZED_FIELD_INFO_SUCCESS =
  "DELETE_NATURAL_SPECIALIZED_FIELD_INFO_SUCCESS";
export const DELETE_NATURAL_SPECIALIZED_FIELD_INFO_FAILED =
  "DELETE_NATURAL_SPECIALIZED_FIELD_INFO_FAILED";

export const POST_APPLICANT_FIELD_INFO_FIELD_INFO =
  "POST_APPLICANT_FIELD_INFO_FIELD_INFO";
export const POST_APPLICANT_FIELD_INFO_FIELD_INFO_SUCCESS =
  "POST_APPLICANT_FIELD_INFO_FIELD_INFO_SUCCESS";
export const POST_APPLICANT_FIELD_INFO_FIELD_INFO_FAILED =
  "POST_APPLICANT_FIELD_INFO_FIELD_INFO_FAILED";

export const DELETE_JUDICIAL_SPECIALIZED_FIELD_INFO =
  "DELETE_JUDICIAL_SPECIALIZED_FIELD_INFO";
export const DELETE_JUDICIAL_SPECIALIZED_FIELD_INFO_SUCCESS =
  "DELETE_JUDICIAL_SPECIALIZED_FIELD_INFO_SUCCESS";
export const DELETE_JUDICIAL_SPECIALIZED_FIELD_INFO_FAILED =
  "DELETE_JUDICIAL_SPECIALIZED_FIELD_INFO_FAILED";

export const POST_APPLICANT_FIELD_INFO_FIELD_JUDICIAL_INFO =
  "POST_APPLICANT_FIELD_INFO_FIELD_JUDICIAL_INFO";
export const POST_APPLICANT_FIELD_INFO_FIELD_JUDICIAL_INFO_SUCCESS =
  "POST_APPLICANT_FIELD_INFO_FIELD_JUDICIAL_INFO_SUCCESS";
export const POST_APPLICANT_FIELD_INFO_FIELD_JUDICIAL_INFO_FAILED =
  "POST_APPLICANT_FIELD_INFO_FIELD_JUDICIAL_INFO_FAILED";

export const NO_INQUIRE_CERTIFICATE_UPLOAD = "NO_INQUIRE_CERTIFICATE_UPLOAD";
export const NO_INQUIRE_CERTIFICATE_UPLOAD_SUCCESS =
  "NO_INQUIRE_CERTIFICATE_UPLOAD_SUCCESS";
export const NO_INQUIRE_CERTIFICATE_UPLOAD_FAILD =
  "NO_INQUIRE_CERTIFICATE_UPLOAD_FAILD";

export const DOWNLOAD_NATURAL_80_HOUR_CERTIFICATE_FIELD_INFO =
  "DOWNLOAD_NATURAL_80_HOUR_CERTIFICATE_FIELD_INFO";
export const DOWNLOAD_NATURAL_80_HOUR_CERTIFICATE_FIELD_INFO_SUCCESS =
  "DOWNLOAD_NATURAL_80_HOUR_CERTIFICATE_FIELD_INFO_SUCCESS";
export const DOWNLOAD_NATURAL_80_HOUR_CERTIFICATE_FIELD_INFO_FAILED =
  "DOWNLOAD_NATURAL_80_HOUR_CERTIFICATE_FIELD_INFO_FAILED";

export const GET_LIST_DOCUMENTS_NATURAL = "GET_LIST_DOCUMENTS_NATURAL";
export const GET_LIST_DOCUMENTS_NATURAL_SUCCESS =
  "GET_LIST_DOCUMENTS_NATURAL_SUCCESS";
export const GET_LIST_DOCUMENTS_NATURAL_FAILED =
  "GET_LIST_DOCUMENTS_NATURAL_FAILED";

export const UPLOAD_DOCUMENTS_NATURAL = "UPLOAD_DOCUMENTS_NATURAL";
export const UPLOAD_DOCUMENTS_NATURAL_SUCCESS =
  "UPLOAD_DOCUMENTS_NATURAL_SUCCESS";
export const UPLOAD_DOCUMENTS_NATURAL_FAILED =
  "UPLOAD_DOCUMENTS_NATURAL_FAILED";

export const REMOVE_DOCUMENTS_NATURAL = "REMOVE_DOCUMENTS_NATURAL";
export const REMOVE_DOCUMENTS_NATURAL_SUCCESS =
  "REMOVE_DOCUMENTS_NATURAL_SUCCESS";
export const REMOVE_DOCUMENTS_NATURAL_FAILED =
  "REMOVE_DOCUMENTS_NATURAL_FAILED";

export const DOWNLOAD_DOCUMENT_NATURAL = "DOWNLOAD_DOCUMENT_NATURAL";
export const DOWNLOAD_DOCUMENT_NATURAL_SUCCESS =
  "DOWNLOAD_DOCUMENT_NATURAL_SUCCESS";
export const DOWNLOAD_DOCUMENT_NATURAL_FAILED =
  "DOWNLOAD_DOCUMENT_NATURAL_FAILED";

export const GET_CERTIFICATE_INFO_LIST_WORK_EXPERIENCE_NATURAL =
  "GET_CERTIFICATE_INFO_LIST_WORK_EXPERIENCE_NATURAL";
export const GET_CERTIFICATE_INFO_LIST_WORK_EXPERIENCE_NATURAL_SUCCESS =
  "GET_CERTIFICATE_INFO_LIST_WORK_EXPERIENCE_NATURAL_SUCCESS";
export const GET_CERTIFICATE_INFO_LIST_WORK_EXPERIENCE_NATURAL_FAILED =
  "GET_CERTIFICATE_INFO_LIST_WORK_EXPERIENCE_NATURAL_FAILED";

export const GET_ALL_INFO_FINAL_APPROVAL = "GET_ALL_INFO_FINAL_APPROVAL";
export const GET_ALL_INFO_FINAL_APPROVAL_SUCCESS =
  "GET_ALL_INFO_FINAL_APPROVAL_SUCCESS";
export const GET_ALL_INFO_FINAL_APPROVAL_FAILED =
  "GET_ALL_INFO_FINAL_APPROVAL_FAILED";

export const GET_ALL_INFO_FINAL_APPROVAL_LEGAL =
  "GET_ALL_INFO_FINAL_APPROVAL_LEGAL";
export const GET_ALL_INFO_FINAL_APPROVAL_LEGAL_SUCCESS =
  "GET_ALL_INFO_FINAL_APPROVAL_LEGAL_SUCCESS";
export const GET_ALL_INFO_FINAL_APPROVAL_LEGAL_FAILED =
  "GET_ALL_INFO_FINAL_APPROVAL_LEGAL_FAILED";

export const DOWNLOAD_DOCUMENT_LEGAL = "DOWNLOAD_DOCUMENT_LEGAL";
export const DOWNLOAD_DOCUMENT_LEGAL_SUCCESS =
  "DOWNLOAD_DOCUMENT_LEGAL_SUCCESS";
export const DOWNLOAD_DOCUMENT_LEGAL_FAILED = "DOWNLOAD_DOCUMENT_LEGAL_FAILED";

export const GET_LIST_DOCUMENTS_JUDICIAL = "GET_LIST_DOCUMENTS_JUDICIAL";
export const GET_LIST_DOCUMENTS_JUDICIAL_SUCCESS =
  "GET_LIST_DOCUMENTS_JUDICIAL_SUCCESS";
export const GET_LIST_DOCUMENTS_JUDICIAL_FAILED =
  "GET_LIST_DOCUMENTS_JUDICIAL_FAILED";

export const REMOVE_DOCUMENTS_JUDICIAL = "REMOVE_DOCUMENTS_JUDICIAL";
export const REMOVE_DOCUMENTS_JUDICIAL_SUCCESS =
  "REMOVE_DOCUMENTS_JUDICIAL_SUCCESS";
export const REMOVE_DOCUMENTS_JUDICIAL_FAILED =
  "REMOVE_DOCUMENTS_JUDICIAL_FAILED";

export const UPLOAD_DOCUMENTS_JUDICIAL = "UPLOAD_DOCUMENTS_JUDICIAL";
export const UPLOAD_DOCUMENTS_JUDICIAL_SUCCESS =
  "UPLOAD_DOCUMENTS_JUDICIAL_SUCCESS";
export const UPLOAD_DOCUMENTS_JUDICIAL_FAILED =
  "UPLOAD_DOCUMENTS_JUDICIAL_FAILED";

export const GET_BIRTH_CITY_PROVINCE_ID = "GET_BIRTH_CITY_PROVINCE_ID";
export const GET_BIRTH_CITY_PROVINCE_ID_SUCCESS =
  "GET_BIRTH_CITY_PROVINCE_ID_SUCCESS";
export const GET_BIRTH_CITY_PROVINCE_ID_FAILED =
  "GET_BIRTH_CITY_PROVINCE_ID_FAILED";

export const GET_RESIDENCE_CITY_PROVINCE_ID = "GET_RESIDENCE_CITY_PROVINCE_ID";
export const GET_RESIDENCE_CITY_PROVINCE_ID_SUCCESS =
  "GET_RESIDENCE_CITY_PROVINCE_ID_SUCCESS";
export const GET_RESIDENCE_CITY_PROVINCE_ID_FAILED =
  "GET_RESIDENCE_CITY_PROVINCE_ID_FAILED";

export const GET_WORK_CITY_PROVINCE_ID = "GET_WORK_CITY_PROVINCE_ID";
export const GET_WORK_CITY_PROVINCE_ID_SUCCESS =
  "GET_WORK_CITY_PROVINCE_ID_SUCCESS";
export const GET_WORK_CITY_PROVINCE_ID_FAILED =
  "GET_WORK_CITY_PROVINCE_ID_FAILED";

export const NATURAL_IS_EXAM_NOT_NEEDED_TRUE =
  "NATURAL_IS_EXAM_NOT_NEEDED_TRUE";
export const NATURAL_IS_EXAM_NOT_NEEDED_FALSE =
  "NATURAL_IS_EXAM_NOT_NEEDED_FALSE";

export const GET_SUB_FIELD_BASED_ON_FIELD = "GET_SUB_FIELD_BASED_ON_FIELD";
export const GET_SUB_FIELD_BASED_ON_FIELD_SUCCESS =
  "GET_SUB_FIELD_BASED_ON_FIELD_SUCCESS";
export const GET_SUB_FIELD_BASED_ON_FIELD_FAILED =
  "GET_SUB_FIELD_BASED_ON_FIELD_FAILED";

export const CHECK_PHONE_NUMBER = "CHECK_PHONE_NUMBER";
export const CHECK_PHONE_NUMBER_SUCCESS = "CHECK_PHONE_NUMBER_SUCCESS";
export const CHECK_PHONE_NUMBER_FAILED = "CHECK_PHONE_NUMBER_FAILED";

export const REGISTRATION_LOGIN = "REGISTRATION_LOGIN";
export const REGISTRATION_LOGIN_SUCCESS = "REGISTRATION_LOGIN_SUCCESS";
export const REGISTRATION_LOGIN_FAILED = "REGISTRATION_LOGIN_FAILED";

export const GET_ADJUSTMENT_FIELD_INFO_NATURAL =
  "GET_ADJUSTMENT_FIELD_INFO_NATURAL";
export const GET_ADJUSTMENT_FIELD_INFO_NATURAL_SUCCESS =
  "GET_ADJUSTMENT_FIELD_INFO_NATURAL_SUCCESS";
export const GET_ADJUSTMENT_FIELD_INFO_NATURAL_FAILED =
  "GET_ADJUSTMENT_FIELD_INFO_NATURAL_FAILED";

//ثبت نام
export const REGISTRATION = "REGISTRATION";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

//فراموشی پسورد
export const FORGET_REGISTRATION = "FORGET_REGISTRATION";
export const FORGRT_REGISTRATION_SUCCESS = "FORGRT_REGISTRATION_SUCCESS";
export const FORGET_REGISTRATION_FAILED = "FORGET_REGISTRATION_FAILED";

export const GET_ALL_ADJUSTER_TYPE = "GET_ALL_ADJUSTER_TYPE";
export const GET_ALL_ADJUSTER_TYPE_SUCCESS = "GET_ALL_ADJUSTER_TYPE_SUCCESS";
export const GET_ALL_ADJUSTER_TYPE_FAILED = "GET_ALL_ADJUSTER_TYPE_FAILED";

// ارجاع در ویرایش ثبت نام
export const REFERER_REGISTERION = "REFERER_REGISTERION";
export const REFERER_REGISTERION_SUCCESS = "REFERER_REGISTERION_SUCCESS";
export const REFERER_REGISTERION_FAILED = "REFERER_REGISTERION_FAILED";

export const GET_NATURAL_DRAFT_FIELD_INFO = "GET_NATURAL_DRAFT_FIELD_INFO";
export const GET_NATURAL_DRAFT_FIELD_INFO_SUCCESS =
  "GET_NATURAL_DRAFT_FIELD_INFO_SUCCESS";
export const GET_NATURAL_DRAFT_FIELD_INFO_FAILED =
  "GET_NATURAL_DRAFT_FIELD_INFO_FAILED";

export const NATURAL_DISABLE_NEXT_BUTTON_FIELDINFO_TRUE =
  "NATURAL_DISABLE_NEXT_BUTTON_FIELDINFO_TRUE";
export const NATURAL_DISABLE_NEXT_BUTTON_FIELDINFO_FALSE =
  "NATURAL_DISABLE_NEXT_BUTTON_FIELDINFO_FALSE";

export const IS_SUBFIELD_INQUIRED_NATURAL_ADD =
  "IS_SUBFIELD_INQUIRED_NATURAL_ADD";
export const IS_SUBFIELD_INQUIRED_NATURAL_REMOVE =
  "IS_SUBFIELD_INQUIRED_NATURAL_REMOVE";

export const DELETE_NATURAL_SUB_FIELD_INFO_EDIT =
  "DELETE_NATURAL_SUB_FIELD_INFO_EDIT";
export const DELETE_NATURAL_SUB_FIELD_INFO_EDIT_SUCCESS =
  "DELETE_NATURAL_SUB_FIELD_INFO_EDIT_SUCCESS";
export const DELETE_NATURAL_SUB_FIELD_INFO_EDIT_FAILED =
  "DELETE_NATURAL_SUB_FIELD_INFO_EDIT_FAILED";

export const NO_INQUIRE_SUBFIELD_CERTIFICATE_UPLOAD =
  "NO_INQUIRE_SUBFIELD_CERTIFICATE_UPLOAD";
export const NO_INQUIRE_SUBFIELD_CERTIFICATE_UPLOAD_SUCCESS =
  "NO_INQUIRE_SUBFIELD_CERTIFICATE_UPLOAD_SUCCESS";
export const NO_INQUIRE_SUBFIELD_CERTIFICATE_UPLOAD_FAILED =
  "NO_INQUIRE_SUBFIELD_CERTIFICATE_UPLOAD_FAILED";

export const DOWNLOAD_RAW_FORM_NATURAL = "DOWNLOAD_RAW_FORM_NATURAL";
export const DOWNLOAD_RAW_FORM_NATURAL_SUCCESS =
  "DOWNLOAD_RAW_FORM_NATURAL_SUCCESS";
export const DOWNLOAD_RAW_FORM_NATURAL_FAILED =
  "DOWNLOAD_RAW_FORM_NATURAL_FAILED";

export const GET_REJECT_REASON_LIST_APPLICANT_DOCUMENT =
  "GET_REJECT_REASON_LIST_APPLICANT_DOCUMENT";
export const GET_REJECT_REASON_LIST_APPLICANT_DOCUMENT_SUCCESS =
  "GET_REJECT_REASON_LIST_APPLICANT_DOCUMENT_SUCCESS";
export const GET_REJECT_REASON_LIST_APPLICANT_DOCUMENT_FAILED =
  "GET_REJECT_REASON_LIST_APPLICANT_DOCUMENT_FAILED";

export const APPLICANT_REJECT_REASON = "APPLICANT_REJECT_REASON";
export const APPLICANT_REJECT_REASON_SUCCESS =
  "APPLICANT_REJECT_REASON_SUCCESS";
export const APPLICANT_REJECT_REASON_FAILED = "APPLICANT_REJECT_REASON_FAILED";

export const WORK_EXPERIENCE_REJECT_REASON = "WORK_EXPERIENCE_REJECT_REASON";
export const WORK_EXPERIENCE_REJECT_REASON_SUCCESS =
  "WORK_EXPERIENCE_REJECT_REASON_SUCCESS";
export const WORK_EXPERIENCE_REJECT_REASON_FAILED =
  "WORK_EXPERIENCE_REJECT_REASON_FAILED";

export const DELETE_JUDICIAL_SUB_FIELD_INFO_EDIT =
  "DELETE_JUDICIAL_SUB_FIELD_INFO_EDIT";
export const DELETE_JUDICIAL_SUB_FIELD_INFO_EDIT_SUCCESS =
  "DELETE_JUDICIAL_SUB_FIELD_INFO_EDIT_SUCCESS";
export const DELETE_JUDICIAL_SUB_FIELD_INFO_EDIT_FAILED =
  "DELETE_JUDICIAL_SUB_FIELD_INFO_EDIT_FAILED";

export const DOWNLOAD_RAW_FORM_CRIMINAL_NATURAL =
  "DOWNLOAD_RAW_FORM_CRIMINAL_NATURAL";
export const DOWNLOAD_RAW_FORM_CRIMINAL_NATURAL_SUCCESS =
  "DOWNLOAD_RAW_FORM_CRIMINAL_NATURAL_SUCCESS";
export const DOWNLOAD_RAW_FORM_CRIMINAL_NATURAL_FAILED =
  "DOWNLOAD_RAW_FORM_CRIMINAL_NATURAL_FAILED";

export const DOWNLOAD_RAW_FORM_NON_ADDICTION_NATURAL =
  "DOWNLOAD_RAW_FORM_NON_ADDICTION_NATURAL";
export const DOWNLOAD_RAW_FORM_NON_ADDICTION_NATURAL_SUCCESS =
  "DOWNLOAD_RAW_FORM_NON_ADDICTION_NATURAL_SUCCESS";
export const DOWNLOAD_RAW_FORM_NON_ADDICTION_NATURAL_FAILED =
  "DOWNLOAD_RAW_FORM_NON_ADDICTION_NATURAL_FAILED";

export const GET_CAPTCHA = "GET_CAPTCHA";
export const GET_CAPTCHA_SUCCESS = "GET_CAPTCHA_SUCCESS";
export const GET_CAPTCHA_FAILED = "GET_CAPTCHA_FAILED";

export const GET_APPLICANT_LAST_STATUS = "GET_APPLICANT_LAST_STATUS";
export const GET_APPLICANT_LAST_STATUS_SUCCESS =
  "GET_APPLICANT_LAST_STATUS_SUCCESS";
export const GET_APPLICANT_LAST_STATUS_FAILED =
  "GET_APPLICANT_LAST_STATUS_FAILED";

export const JUDICIAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO =
  "JUDICIAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO";
export const JUDICIAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_SUCCESS =
  "JUDICIAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_SUCCESS";
export const JUDICIAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_FAILED =
  "JUDICIAL_EDIT_FIELD_INFO_GET_SUB_FIELD_INFO_FAILED";

export const JUDICIAL_EDIT_INQUIRE_FIELD_CERTIFICATE =
  "JUDICIAL_EDIT_INQUIRE_FIELD_CERTIFICATE";
export const JUDICIAL_EDIT_INQUIRE_FIELD_CERTIFICATE_SUCCESS =
  "JUDICIAL_EDIT_INQUIRE_FIELD_CERTIFICATE_SUCCESS";
export const JUDICIAL_EDIT_INQUIRE_FIELD_CERTIFICATE_FAILED =
  "JUDICIAL_EDIT_INQUIRE_FIELD_CERTIFICATE_FAILED";
