export const GET_HOLIDAY_LIST = "GET_HOLIDAY_LIST";
export const GET_HOLIDAY_LIST_SUCCESS = "GET_HOLIDAY_LIST_SUCCESS";
export const GET_HOLIDAY_LIST_FAILD = "GET_HOLIDAY_LIST_FAILD";

export const SEND_NAT_AND_REG_CODES = "SEND_NAT_AND_REG_CODES";
export const SEND_NAT_AND_REG_CODES_SUCCESS = "SEND_NAT_AND_REG_CODES_SUCCESS";
export const SEND_NAT_AND_REG_CODES_FAILED = "SEND_NAT_AND_REG_CODES_FAILED";

export const USER_EDIT_SET_TRUE = "USER_EDIT_SET_TRUE";
export const USER_EDIT_SET_FALSE = "USER_EDIT_SET_FALSE";

export const IS_COME_FROM_REGISTRATION_TRUE = "IS_COME_FROM_REGISTRATION_TRUE";
export const IS_COME_FROM_REGISTRATION_FALSE =
  "IS_COME_FROM_REGISTRATION_FALSE";

export const GET_COURSE_TYPE = "GET_COURSE_TYPE";
export const GET_COURSE_TYPE_SUCCESS = "GET_COURSE_TYPE_SUCCESS";
export const GET_COURSE_TYPE_FAILED = "GET_COURSE_TYPE_FAILED";

export const REGISTRATION_COMPONENT_UNMOUNT = "REGISTRATION_COMPONENT_UNMOUNT";

export const GET_VALID_COURSES = "GET_VALID_COURSES";
export const GET_VALID_COURSES_SUCCESS = "GET_VALID_COURSES_SUCCESS";
export const GET_VALID_COURSES_FAILD = "GET_VALID_COURSES_FAILD";

export const REGISTRATION_FINALIZE = "REGISTRATION_FINALIZE";
export const REGISTRATION_FINALIZE_SUCCESS = "REGISTRATION_FINALIZE_SUCCESS";
export const REGISTRATION_FINALIZE_FAILED = "REGISTRATION_FINALIZE_FAILED";

export const GET_FIELD_INFO_DRAFT = "GET_FIELD_INFO_DRAFT";
export const GET_FIELD_INFO_DRAFT_SUCCESS = "GET_FIELD_INFO_DRAFT_SUCCESS";
export const GET_FIELD_INFO_DRAFT_FAILED = "GET_FIELD_INFO_DRAFT_FAILED";

export const POST_FIELD_INFO_DRAFT = "POST_FIELD_INFO_DRAFT";
export const POST_FIELD_INFO_DRAFT_SUCCESS = "POST_FIELD_INFO_DRAFT_SUCCESS";
export const POST_FIELD_INFO_DRAFT_FAILED = "POST_FIELD_INFO_DRAFT_FAILED";

export const UPLOAD_FIELD_INFO_CERTIFICATE_DRAFT =
  "UPLOAD_FIELD_INFO_CERTIFICATE_DRAFT";
export const UPLOAD_FIELD_INFO_CERTIFICATE_DRAFT_SUCCESS =
  "UPLOAD_FIELD_INFO_CERTIFICATE_DRAFT_SUCCESS";
export const UPLOAD_FIELD_INFO_CERTIFICATE_DRAFT_FAILED =
  "UPLOAD_FIELD_INFO_CERTIFICATE_DRAFT_FAILED";

export const INQUIRE_SUB_FIELD_CERTIFICATE_DRAFT =
  "INQUIRE_SUB_FIELD_CERTIFICATE_DRAFT";
export const INQUIRE_SUB_FIELD_CERTIFICATE_DRAFT_SUCCESS =
  "INQUIRE_SUB_FIELD_CERTIFICATE_DRAFT_SUCCESS";
export const INQUIRE_SUB_FIELD_CERTIFICATE_DRAFT_FAILED =
  "INQUIRE_SUB_FIELD_CERTIFICATE_DRAFT_FAILED";

export const INQUIRE_FIELD_INFO_DRAFT = "INQUIRE_FIELD_INFO_DRAFT";
export const INQUIRE_FIELD_INFO_DRAFT_SUCCESS =
  "INQUIRE_FIELD_INFO_DRAFT_SUCCESS";
export const INQUIRE_FIELD_INFO_DRAFT_FAILED =
  "INQUIRE_FIELD_INFO_DRAFT_FAILED";

export const UPLOAD_SUB_FIELD_INFO_CERTIFICATE_DRAFT =
  "UPLOAD_SUB_FIELD_INFO_CERTIFICATE_DRAFT";
export const UPLOAD_SUB_FIELD_INFO_CERTIFICATE_DRAFT_SUCCESS =
  "UPLOAD_SUB_FIELD_INFO_CERTIFICATE_DRAFT_SUCCESS";
export const UPLOAD_SUB_FIELD_INFO_CERTIFICATE_DRAFT_FAILED =
  "UPLOAD_SUB_FIELD_INFO_CERTIFICATE_DRAFT_FAILED";

export const POST_SUB_FIELD_INFO_DRAFT = "POST_SUB_FIELD_INFO_DRAFT";
export const POST_SUB_FIELD_INFO_DRAFT_SUCCESS =
  "POST_SUB_FIELD_INFO_DRAFT_SUCCESS";
export const POST_SUB_FIELD_INFO_DRAFT_FAILED =
  "POST_SUB_FIELD_INFO_DRAFT_FAILED";

export const POST_IS_EXAM_NOT_NEEDED_DRAFT = "POST_IS_EXAM_NOT_NEEDED_DRAFT";
export const POST_IS_EXAM_NOT_NEEDED_DRAFT_SUCCESS =
  "POST_IS_EXAM_NOT_NEEDED_DRAFT_SUCCESS";
export const POST_IS_EXAM_NOT_NEEDED_DRAFT_FAILED =
  "POST_IS_EXAM_NOT_NEEDED_DRAFT_FAILED";

export const DELETE_SUB_FIELD_INFO_DRAFT = "DELETE_SUB_FIELD_INFO_DRAFT";
export const DELETE_SUB_FIELD_INFO_DRAFT_SUCCESS =
  "DELETE_SUB_FIELD_INFO_DRAFT_SUCCESS";
export const DELETE_SUB_FIELD_INFO_DRAFT_FAILED =
  "DELETE_SUB_FIELD_INFO_DRAFT_FAILED";

export const IS_LOGGED_IN_OR_INQUIRED_TRUE = "IS_LOGGED_IN_OR_INQUIRED_TRUE";
export const IS_LOGGED_IN_OR_INQUIRED_FALSE = "IS_LOGGED_IN_OR_INQUIRED_FALSE";

export const POST_IS_EXAM_NOT_NEEDED_EDIT = "POST_IS_EXAM_NOT_NEEDED_EDIT";
export const POST_IS_EXAM_NOT_NEEDED_EDIT_SUCCESS =
  "POST_IS_EXAM_NOT_NEEDED_EDIT_SUCCESS";
export const POST_IS_EXAM_NOT_NEEDED_EDIT_FAILED =
  "POST_IS_EXAM_NOT_NEEDED_EDIT_FAILED";

export const POST_IS_EXAM_NOT_NEEDED_EDIT_JUDICIAL =
  "POST_IS_EXAM_NOT_NEEDED_EDIT_JUDICIAL";
export const POST_IS_EXAM_NOT_NEEDED_EDIT_JUDICIAL_SUCCESS =
  "POST_IS_EXAM_NOT_NEEDED_EDIT_JUDICIAL_SUCCESS";
export const POST_IS_EXAM_NOT_NEEDED_EDIT_JUDICIAL_FAILED =
  "POST_IS_EXAM_NOT_NEEDED_EDIT_JUDICIAL_FAILED";
