//legal Draft Company Info
export const LEGAL_DRAFT_COMPANY_INFO = "LEGAL_DRAFT_COMPANY_INFO";
export const LEGAL_DRAFT_COMPANY_INFO_SUCCESS =
  "LEGAL_DRAFT_COMPANY_INFO_SUCCESS";
export const LEGAL_DRAFT_COMPANY_INFO_FAILD = "LEGAL_DRAFT_COMPANY_INFO_FAILD";
export const LEGAL_DRAFT_COMPANY_INFO_GET_SUCCESS =
  "LEGAL_DRAFT_COMPANY_INFO_GET_SUCCESS";

  export const PERSONAL_INFO ="PERSONAL_INFO";
export const PERSONAL_INFO_FAILD = "PERSONAL_INFO_FAILD";
export const PERSONAL_INFO_SUCCESS =
  "PERSONAL_INFO_SUCCESS";
//COMPANY TYPES
 export const LEGAL_COMPANY_TYPES="LEGAL_COMPANY_TYPES"
 export const LEGAL_COMPANY_TYPES_SUCCESS="LEGAL_COMPANY_TYPES_SUCCESS"
 export const LEGAL_COMPANY_TYPES_FAILD="LEGAL_COMPANY_TYPES_FAILD"

//legal Draft Work Location
export const LEGAL_DRAFT_WORK_LOCATION_INFO = "LEGAL_DRAFT_WORK_LOCATION_INFO";
export const LEGAL_DRAFT_WORK_LOCATION_INFO_SUCCESS =
  "LEGAL_DRAFT_WORK_LOCATION_INFO_SUCCESS";
export const LEGAL_DRAFT_WORK_LOCATION_INFO_FAILD =
  "LEGAL_DRAFT_WORK_LOCATION_INFO_FAILD";


// legal SubFeild
export const BOARD_MEMBER_NATURAL_SUB_FIELD = "BOARD_MEMBER_NATURAL_SUB_FIELD";
export const BOARD_MEMBER_NATURAL_SUB_FIELD_SUCCESS =
  "BOARD_MEMBER_NATURAL_SUB_FIELD_SUCCESS";
export const BOARD_MEMBER_NATURAL_SUB_FIELD_FAILD =
  "BOARD_MEMBER_NATURAL_SUB_FIELD_FAILD";



export const LEGAL_DRAFT_WORK_LOCATION_GET_INFO =
  "LEGAL_DRAFT_WORK_LOCATION_GET_INFO";
export const LEGAL_DRAFT_WORK_LOCATION_GET_INFO_SUCCESS =
  "LEGAL_DRAFT_WORK_LOCATION_GET_INFO_SUCCESS";
export const LEGAL_DRAFT_WORK_LOCATION_GET_INFO_FAILD =
  "LEGAL_DRAFT_WORK_LOCATION_GET_INFO_FAILD";
//legal Draft Board Of Directors
export const LEGAL_DRAFT_BOARD_MEMBER = "LEGAL_DRAFT_BOARD_MEMBER";
export const LEGAL_DRAFT_BOARD_MEMBER_SUCCESS =
  "LEGAL_DRAFT_BOARD_MEMBER_SUCCESS";
export const LEGAL_DRAFT_BOARD_MEMBER_FAILD = "LEGAL_DRAFT_BOARD_MEMBER_FAILD";

//legal Draft Work experience
export const LEGAL_DRAFT_WORK_EXPERIENCE = "LEGAL_DRAFT_WORK_EXPERIENCE";
export const LEGAL_DRAFT_WORK_EXPERIENCE_SUCCESS =
  "LEGAL_DRAFT_WORK_EXPERIENCE_SUCCESS";
export const LEGAL_DRAFT_WORK_EXPERIENCE_FAILD =
  "LEGAL_DRAFT_WORK_EXPERIENCE_FAILD";

//legal draft CEO Work Experience
export const LEGAL_DRAFT_CEO_WORK_EXPERIENCE_GET_ALL_INFO =
  "LEGAL_DRAFT_CEO_WORK_EXPERIENCE_GET_ALL_INFO";
export const LEGAL_DRAFT_CEO_WORK_EXPERIENCE_GET_ALL_INFO_SUCCESS =
  "LEGAL_DRAFT_CEO_WORK_EXPERIENCE_GET_ALL_INFO_SUCCESS";
export const LEGAL_DRAFT_CEO_WORK_EXPERIENCE_GET_ALL_INFO_FAILD =
  "LEGAL_DRAFT_CEO_WORK_EXPERIENCE_GET_ALL_INFO_FAILD";

export const LEGAL_DRAFT_BOARD_MEMBER_GET_ALL_INFO =
  "LEGAL_DRAFT_BOARD_MEMBER_GET_ALL_INFO";
export const LEGAL_DRAFT_BOARD_MEMBER_GET_ALL_INFO_SUCCESS =
  "LEGAL_DRAFT_BOARD_MEMBER_GET_ALL_INFO_SUCCESS";
export const LEGAL_DRAFT_BOARD_MEMBER_GET_ALL_INFO_FAILD =
  "LEGAL_DRAFT_BOARD_MEMBER_GET_ALL_INFO_FAILD";

//patch data for board member
export const LEGAL_DRAFT_PATCH_BOARD_MEMBER = "LEGAL_DRAFT_PATCH_BOARD_MEMBER";
export const LEGAL_DRAFT_PATCH_BOARD_MEMBER_SUCCESS =
  "LEGAL_DRAFT_PATCH_BOARD_MEMBER_SUCCESS";
export const LEGAL_DRAFT_PATCH_BOARD_MEMBER_FAILD =
  "LEGAL_DRAFT_PATCH_BOARD_MEMBER_FAILD";

//card work experience for CEO work history legal draft
export const LEGAL_DRAFT_CARD_WORK_EXPERIENCE =
  "LEGAL_DRAFT_CARD_WORK_EXPERIENCE";
export const LEGAL_DRAFT_CARD_WORK_EXPERIENCE_SUCCESS =
  "LEGAL_DRAFT_CARD_WORK_EXPERIENCE_SUCCESS";
export const LEGAL_DRAFT_CARD_WORK_EXPERIENCE_FAILD =
  "LEGAL_DRAFT_CARD_WORK_EXPERIENCE_FAILD";

//list legal draft work experience
export const LIST_LEGAL_DRAFT_WORK_EXPERIENCE =
  "LIST_LEGAL_DRAFT_WORK_EXPERIENCE";
export const LIST_LEGAL_DRAFT_WORK_EXPERIENCE_SUCCESS =
  "LIST_LEGAL_DRAFT_WORK_EXPERIENCE_SUCCESS";
export const LIST_LEGAL_DRAFT_WORK_EXPERIENCE_FAILD =
  "LIST_LEGAL_DRAFT_WORK_EXPERIENCE_FAILD";

//list legal draft CEO work experience
export const LIST_LEGAL_DRAFT_CEO_WORK_EXPERIENCE =
  "LIST_LEGAL_DRAFT_CEO_WORK_EXPERIENCE";
export const LIST_LEGAL_DRAFT_CEO_WORK_EXPERIENCE_SUCCESS =
  "LIST_LEGAL_DRAFT_CEO_WORK_EXPERIENCE_SUCCESS";
export const LIST_LEGAL_DRAFT_CEO_WORK_EXPERIENCE_FAILD =
  "LIST_LEGAL_DRAFT_CEO_WORK_EXPERIENCE_FAILD";

//upload legal draft work experience certificate
export const UPLOAD_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "UPLOAD_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const UPLOAD_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "UPLOAD_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const UPLOAD_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "UPLOAD_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

// delete legal draft work experience certificate
export const DELETE_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE =
  "DELETE_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE";
export const DELETE_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS =
  "DELETE_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_SUCCESS";
export const DELETE_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD =
  "DELETE_LEGAL_DRAFT_WORK_EXPERIENCE_CERTIFICATE_FAILD";

//delelte legal draft CEO work history or experience
export const DELETE_LEGAL_DRAFT_CEO_WORK_HISTORY =
  "DELETE_LEGAL_DRAFT_CEO_WORK_HISTORY";
export const DELETE_LEGAL_DRAFT_CEO_WORK_HISTORY_SUCCESS =
  "DELETE_LEGAL_DRAFT_CEO_WORK_HISTORY_SUCCESS";
export const DELETE_LEGAL_DRAFT_CEO_WORK_HISTORY_FAILD =
  "DELETE_LEGAL_DRAFT_CEO_WORK_HISTORY_FAILD";

//patch CEO work experience for edit
export const LEGAL_DRAFT_PATCH_CEO_WORK_EXPERIENCE =
  "LEGAL_DRAFT_PATCH_CEO_WORK_EXPERIENCE";
export const LEGAL_DRAFT_PATCH_CEO_WORK_EXPERIENCE_SUCCESS =
  "LEGAL_DRAFT_PATCH_CEO_WORK_EXPERIENCE_SUCCESS";
export const LEGAL_DRAFT_PATCH_CEO_WORK_EXPERIENCE_FAILD =
  "LEGAL_DRAFT_PATCH_CEO_WORK_EXPERIENCE_FAILD";

//delete card board
export const DELETE_LEGAL_DRAFT_BOARD_MEMBER =
  "DELETE_LEGAL_DRAFT_BOARD_MEMBER";
export const DELETE_LEGAL_DRAFT_BOARD_MEMBER_SUCCESS =
  "DELETE_LEGAL_DRAFT_BOARD_MEMBER_SUCCESS";
export const DELETE_LEGAL_DRAFT_BOARD_MEMBER_FAILD =
  "DELETE_LEGAL_DRAFT_BOARD_MEMBER_FAILD";

//legal Draft stockholders
export const LEGAL_DRAFT_STOCKHOLDER = "LEGAL_DRAFT_STOCKHOLDER ";
export const LEGAL_DRAFT_STOCKHOLDER_SUCCESS =
  "LEGAL_DRAFT_STOCKHOLDER_SUCCESS ";
export const LEGAL_DRAFT_STOCKHOLDER_FAILD = "LEGAL_DRAFT_STOCKHOLDER_FAILD ";

//list of legal draft stockholders
export const LIST_LEGAL_DRAFT_STOCKHOLDER = "LIST_LEGAL_DRAFT_STOCKHOLDER";
export const LIST_LEGAL_DRAFT_STOCKHOLDER_SUCCESS =
  "LIST_LEGAL_DRAFT_STOCKHOLDER_SUCCESS";
export const LIST_LEGAL_DRAFT_STOCKHOLDER_FAILD =
  "LIST_LEGAL_DRAFT_STOCKHOLDER_FAILD";

// delete stockholder
export const DELETE_LEGAL_DRAFT_STOCKHOLDER = "DELETE_LEGAL_DRAFT_STOCKHOLDER";
export const DELETE_LEGAL_DRAFT_STOCKHOLDER_SUCCESS =
  "DELETE_LEGAL_DRAFT_STOCKHOLDER_SUCCESS";
export const DELETE_LEGAL_DRAFT_STOCKHOLDER_FAILD =
  "DELETE_LEGAL_DRAFT_STOCKHOLDER_FAILD";

// get info stockholder for edit
export const LEGAL_DRAFT_STOCKHOLDET_GET_ALL_INFO =
  "LEGAL_DRAFT_STOCKHOLDET_GET_ALL_INFO";
export const LEGAL_DRAFT_STOCKHOLDET_GET_ALL_INFO_SUCCESS =
  "LEGAL_DRAFT_STOCKHOLDET_GET_ALL_INFO_SUCCESS";
export const LEGAL_DRAFT_STOCKHOLDET_GET_ALL_INFO_FAILD =
  "LEGAL_DRAFT_STOCKHOLDET_GET_ALL_INFO_FAILD";

//patch stockholder for edit
export const LEGAL_DRAFT_PATCH_STOCKHOLDER = "LEGAL_DRAFT_PATCH_STOCKHOLDER";
export const LEGAL_DRAFT_PATCH_STOCKHOLDER_SUCCESS =
  "LEGAL_DRAFT_PATCH_STOCKHOLDER_SUCCESS";
export const LEGAL_DRAFT_PATCH_STOCKHOLDER_FAILD =
  "LEGAL_DRAFT_PATCH_STOCKHOLDER_FAILD";

//legal Draft Staff
export const LEGAL_DRAFT_EMPLOYEE = "LEGAL_DRAFT_EMPLOYEE";
export const LEGAL_DRAFT_EMPLOYEE_SUCCESS = "LEGAL_DRAFT_EMPLOYEE_SUCCESS";
export const LEGAL_DRAFT_EMPLOYEE_FAILD = "LEGAL_DRAFT_EMPLOYEE_FAILD";

//list employee
export const LIST_LEGAL_DRAFT_EMPLOYEE = "LIST_LEGAL_DRAFT_EMPLOYEE";
export const LIST_LEGAL_DRAFT_EMPLOYEE_SUCCESS =
  "LIST_LEGAL_DRAFT_EMPLOYEE_SUCCESS";
export const LIST_LEGAL_DRAFT_EMPLOYEE_FAILD =
  "LIST_LEGAL_DRAFT_EMPLOYEE_FAILD";

//delete employee
export const DELETE_LEGAL_DRAFT_EMPLOYEE = "DELETE_LEGAL_DRAFT_EMPLOYEE";
export const DELETE_LEGAL_DRAFT_EMPLOYEE_SUCCESS =
  "DELETE_LEGAL_DRAFT_EMPLOYEE_SUCCESS";
export const DELETE_LEGAL_DRAFT_EMPLOYEE_FAILD =
  "DELETE_LEGAL_DRAFT_EMPLOYEE_FAILD";

//get all info for employee to edit
export const LEGAL_DRAFT_EMPLOYEE_GET_ALL_INFO =
  "LEGAL_DRAFT_EMPLOYEE_GET_ALL_INFO";
export const LEGAL_DRAFT_EMPLOYEE_GET_ALL_INFO_SUCCESS =
  "LEGAL_DRAFT_EMPLOYEE_GET_ALL_INFO_SUCCESS";
export const LEGAL_DRAFT_EMPLOYEE_GET_ALL_INFO_FAILD =
  "LEGAL_DRAFT_EMPLOYEE_GET_ALL_INFO_FAILD";

//patch info related employee
export const LEGAL_DRAFT_PATCH_EMPLOYEE = "LEGAL_DRAFT_PATCH_EMPLOYEE";
export const LEGAL_DRAFT_PATCH_EMPLOYEE_SUCCESS =
  "LEGAL_DRAFT_PATCH_EMPLOYEE_SUCCESS";
export const LEGAL_DRAFT_PATCH_EMPLOYEE_FAILD =
  "LEGAL_DRAFT_PATCH_EMPLOYEE_FAILD";

//legal Draft Document
export const LEGAL_DRAFT_DOCUMENT = "LEGAL_DRAFT_DOCUMENT";
export const LEGAL_DRAFT_DOCUMENT_SUCCESS = "LEGAL_DRAFT_DOCUMENT_SUCCESS";
export const LEGAL_DRAFT_DOCUMENT_FAILD = "LEGAL_DRAFT_DOCUMENT_FAILD";

//legalwork experience next button
export const LEGAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_TRUE =
  "LEGAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_TRUE";
export const LEGAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_FALSE =
  "LEGAL_DRAFT_DISABLE_NEXT_BUTTON_WORK_EXPERIENCE_FALSE";

export const REGISTRATION_FINALIZE_LEGAL = "REGISTRATION_FINALIZE_LEGAL";
export const REGISTRATION_FINALIZE_LEGAL_SUCCESS =
  "REGISTRATION_FINALIZE_LEGAL_SUCCESS";
export const REGISTRATION_FINALIZE_LEGAL_FAILED =
  "REGISTRATION_FINALIZE_LEGAL_FAILED";

export const GET_DOCUMENTS_LEGAL = "GET_DOCUMENTS_LEGAL";
export const GET_DOCUMENTS_LEGAL_SUCCESS = "GET_DOCUMENTS_LEGAL_SUCCESS";
export const GET_DOCUMENTS_LEGAL_FAILED = "GET_DOCUMENTS_LEGAL_FAILED";

export const DELETE_LEGAL_DOCUMENT = "DELETE_LEGAL_DOCUMENT";
export const DELETE_LEGAL_DOCUMENT_SUCCESS = "DELETE_LEGAL_DOCUMENT_SUCCESS";
export const DELETE_LEGAL_DOCUMENT_FAILED = "DELETE_LEGAL_DOCUMENT_FAILED";

export const UPLOAD_DOCUMENT_LEGAL = "UPLOAD_DOCUMENT_LEGAL";
export const UPLOAD_DOCUMENT_LEGAL_SUCCESS = "UPLOAD_DOCUMENT_LEGAL_SUCCESS";
export const UPLOAD_DOCUMENT_LEGAL_FAILED = "UPLOAD_DOCUMENT_LEGAL_FAILED";

export const LEGAL_GET_COMPANY_INFO = "LEGAL_GET_COMPANY_INFO";
export const LEGAL_GET_COMPANY_INFO_SUCCESS = "LEGAL_GET_COMPANY_INFO_SUCCESS";
export const LEGAL_GET_COMPANY_INFO_FAILED = "LEGAL_GET_COMPANY_INFO_FAILED";

export const GET_WORK_CITY_PROVINCE_ID_LEGAL =
  "GET_WORK_CITY_PROVINCE_ID_LEGAL";
export const GET_WORK_CITY_PROVINCE_ID_LEGAL_SUCCESS =
  "GET_WORK_CITY_PROVINCE_ID_LEGAL_SUCCESS";
export const GET_WORK_CITY_PROVINCE_ID_LEGAL_FAILED =
  "GET_WORK_CITY_PROVINCE_ID_LEGAL_FAILED";

export const GET_BIRTH_CITY_PROVINCE_ID_LEGAL =
  "GET_BIRTH_CITY_PROVINCE_ID_LEGAL";
export const GET_BIRTH_CITY_PROVINCE_ID_LEGAL_SUCCESS =
  "GET_BIRTH_CITY_PROVINCE_ID_LEGAL_SUCCESS";
export const GET_BIRTH_CITY_PROVINCE_ID_LEGAL_FAILED =
  "GET_BIRTH_CITY_PROVINCE_ID_LEGAL_FAILED";

export const IS_ADD_MEMBER_CLICKED_TRUE = "IS_ADD_MEMBER_CLICKED_TRUE";
export const IS_ADD_MEMBER_CLICKED_FALSE = "IS_ADD_MEMBER_CLICKED_FALSE";
