export enum workTaskFlowId {
  InitialSubmissionApplicant = 0,
  AdmissionExpert = 1,
  ReturnToApplicant = 2,
  RejectionAdmissionExpert = 3,
  InterviewInvitation = 4,
  RejectedInInterview = 5,
  Absence = 6,
  ReadyToInterview = 7,
  ReturnToApplicantToCompleteDossier = 8,
  CompletedDossier = 9,
  OfficeBoss = 10,
  Deputy = 11,
  GeneralManager = 12,
  FinalReject = 13,
  ExistingEvaluator = 14,
}

export enum workFlowTask {
  InitialSubmissionApplicant = "ارسال اولیه متقاضی",
  AdmissionExpert = "کارشناس پذیرش",
  ReturnToApplicant = "برگشت به متقاضی",
  RejectionAdmissionExpert = "رد کارشناس پذیرش",
  ReadyToInterview = "آماده به مصاحبه",
  InterviewInvitation = "دعوت به مصاحبه",
  RejectedInInterview = "مردود در مصاحبه",
  Absence = "غایب در مصاحبه",
  ReturnToApplicantToCompleteDossier = "بازگشت به متقاضی جهت تکمیل پرونده",
  CompletedDossier = "پرونده تکمیل شده",
  OfficeBoss = "رئیس اداره",
  Deputy = "معاون",
  GeneralManager = "مدیر کل",
  ExistingEvaluator = "ارزیاب موجود",
  FinalReject = "رد نهایی",
}
